### PR TITLE
Xref travis

### PR DESCRIPTION
**Pull request by fenollp**
**Depends on #1001**

Before merging we need to sort out these last errors:
```
Xref: undefined_function_calls
               blackhole_sup:start_link,,,,,,,,,,,,,,,,,,,,/0                calls undefined                         cowboy:start_http/4
                    crossbar:maybe_start_plaintext,,,,,,,,,/1                calls undefined                         cowboy:start_http/4
                    crossbar:start_ssl,,,,,,,,,,,,,,,,,,,,,/1                calls undefined                         cowboy:start_https/4
        ecallmgr_fs_conferen:send_conference_event,,,,,,,,,/3                calls undefined                wapi_conference:publish_conference_event/2
                         fax:start_link,,,,,,,,,,,,,,,,,,,,/0                calls undefined                         cowboy:start_http/4
                     gcm_api:retry_after_from,,,,,,,,,,,,,,/1                calls undefined                          qdate:to_unixtime/1
                     gcm_api:retry_after_from,,,,,,,,,,,,,,/1                calls undefined                          qdate:unixtime/0
              wh_media_proxy:maybe_start_plaintext,,,,,,,,,/1                calls undefined                         cowboy:start_http/4
              wh_media_proxy:maybe_start_ssl,,,,,,,,,,,,,,,/1                calls undefined                         cowboy:start_https/4
```

**Are these false positives?**
With these left untouched, *every Travis CI build will fail with error 9* (there's 9 errors).

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
The `cowboy:start_http(s)` functions exist. I think xref needs updating to find the right cowboy.beam perhaps?

Ignore the qdate ones for now; gcm is a third-party dep in the pusher app.

Need to fix the ecallmgr_fs_conference one though.

**Comment by fenollp** [comment]
Ah. Got it.
Adding the `./deps/` didn't solve anything, but showed the reason of those `cowboy` false positives:
rabbitmq clashes with a lot of things and with this module (multiple times!).
I'll add those to the filter…

**Comment by fenollp** [comment]
`make test` fails because of proper. Not sure we can fix that…

**Comment by jamesaimonetti** [comment]
Let's make a new target for running proper-related tests and a new macro at compile time.

So -DTEST and `ifdef(TEST).` for eunit, and maybe -DPROPER and `-ifdef(PROPER).` for Proper-related tests.

**Comment by fenollp** [comment]
@jamesaimonetti READY

**Pull request merged**
