### PR TITLE
KAZOO-4890: crossbar returns parked_calls document

### PR DESCRIPTION
**Pull request by jamhed**

### CODE REVIEW

**Comment by fenollp** [comment]
No docs?

**Comment by fenollp** [comment]
I'm talking about ref & accompanying markdown docs + the updated swagger file.

**Comment by jamesaimonetti** [comment]
@jamhed you can generate a stub version of the doc and update swagger by:

```erlang
1> cb_api_endpoints:to_ref_doc().
skipping cb_limits_v1 version <<"v1">>
skipping cb_users_v1 version <<"v1">>
skipping cb_devices_v1 version <<"v1">>                                                       |                                                                                              
skipping cb_lists_v1 version <<"v1">>
skipping cb_vmboxes_v1 version <<"v1">>
skipping cb_phone_numbers_v1 version <<"v1">>
ok
2> cb_api_endpoints:to_swagger_json().                                   |                                                                                              
"checking /home/james/local/git/2600hz/kazoo/scripts/../applications/crossbar/priv/couchdb/swagger/swagger.json\n"
```

**Comment by fenollp** [comment]
@jamhed thanks :)

**Pull request merged**
