### PR TITLE
PISTON-1049: j5_channels: handle empty string presence IDs (don't crash)

### PR DESCRIPTION
**Pull request by danielfinke**
Turns out, users may erroneously set their presence ID to a single space (or similar) and this leads to a blank username in the To field. j5_channels was not handling this and was crashing whenever those users placed calls.

### CODE REVIEW

**Comment by danielfinke** [comment]
Tests appear unrelated to the content of this PR.

**Comment by lazedo** [comment]
what does ` presence ID` fit in this change ?

**Comment by danielfinke** [comment]
@lazedo meaning the `presence_id` field on a user
It affects the To field on the outbound leg if that user is called. In our case it was in a ring group.

**Comment by lazedo** [comment]
did reproduced this in master ? would like to see that because its not supposed to

**Comment by jamesaimonetti** [comment]
@danielfinke any chance you reproduced this on master?

**Comment by danielfinke** [comment]
@jamesaimonetti I haven't tried yet, sorry. Been super busy. I can try to prioritize it for sometime this week and get back to you.

**Comment by lazedo** [comment]
@danielfinke no worries, since this is a simple file pr, just reopen after the breakening

**Pull request closed without merging**
