### PR TITLE
colorize console output

### PR DESCRIPTION
**Pull request by jamhed**

### CODE REVIEW

**Comment by fenollp** [comment]
Hey @jamhed could you add this to ci-sysconfig too?

**Comment by jamhed** [comment]
@fenollp, sure

**Comment by fenollp** [comment]
Thanks!
Hm last test in circle is not using the colors:

```
12:06:41.123 [error] |0000000000|lager_handler_watcher:130 (<0.2202.0>) Lager failed to install handler colored into lager_event, retrying later : {'EXIT',
                                                                            {undef,
                                                                             [{colored,
                                                                               init,
                                                                               [true],
                                                                               []},
                                                                              {gen_event,
                                                                               server_add_handler,
                                                                               4,
                                                                               [{file,
                                                                                 "gen_event.erl"},
                                                                                {line,
                                                                                 434}]},
                                                                              {gen_event,
                                                                               handle_msg,
                                                                               5,
                                                                               [{file,
                                                                                 "gen_event.erl"},
                                                                                {line,
                                                                                 279}]},
                                                                              {proc_lib,
                                                                               init_p_do_apply,
                                                                               3,
                                                                               [{file,
                                                                                 "proc_lib.erl"},
                                                                                {line,
                                                                                 240}]}]}}
```

**Comment by jamhed** [comment]
@fenollp, I've tried ci-sys.conf with actual console, and it works. Maybe circle-ci is doing something with it?

**Comment by fenollp** [comment]
@jamhed Nice! Thanks!

**Pull request merged**
