### PR TITLE
KAZOO-5914: Fixed caller_id_number and caller_id_name formating

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by lazedo** [comment]
@sergey-safarov what is intent here ? can you provide your use case ?

**Comment by sergey-safarov** [comment]
Hello Luis @lazedo 
This fix for [KAZOO-5914](https://2600hz.atlassian.net/browse/KAZOO-5914)
This fix is done by customer request. I will request customer to make comments.
From my view i prefer see numbers in international format with leading `+`. After this PR feature now works again.

**Comment by lazedo** [comment]
@sergey-safarov can you explain `feature now works again` ? i think the code you're changing is quite old an d there's already been discussion on changing things here

**Comment by sergey-safarov** [comment]
@lazedo i tested this feature `4.2` branch and found this not working.
Also make [simple search](https://github.com/2600hz/kazoo/pulls?utf8=%E2%9C%93&q=is%3Apr+caller_id_number) in PR and not found this

I sure this code is introduced in commit f1da809dfb720e503a23e361b403d0b8210705eb.
May be commit is discussed but think is not public.

**Comment by sergey-safarov** [comment]
Two additionally related commits
5a1fe167e1dc2efb2c0725a6ace3c22299c20c0d
e9aaef1cc5d7c87b49b064785def127edc716bce

**Comment by sergey-safarov** [comment]
one more
652e1a00ede879fe6fe0d249578859543e82a3bc - feature documentation
Searched string `The caller ID presented to the device can be altered`

**Comment by TheEvilCoder42** [comment]
Since there's no possibility to open an issue, and this PR is about the same direction, I'm hijacking it..

I'm trying to change the displayed caller-id-name and caller-id-number to the original value from the caller when forwarding an outgoing call through pivot.
Currently the number from Kazoo is shown when the call arrives at the forwarded destination, although I see the correct values in the Freeswitch logs, in the headers of the sip packets as well as in their Remote-Party-ID header.

This is the Kazoo Json I'm returning from the pivot request (the values get inserted from the incoming request):
```
{
    "module": "set_cid",
    "data": {
        "caller_id_name": "[original caller name]",
        "caller_id_number": "[original caller number]"
    },
    "children": {
        "_": {
            "module": "resources",
            "data": {
                "use_local_resources": false,
                "to_did": "[number to forward to]"
            }
        }
    }
}
```

I get the following error every time a call passes the returned actions:
```
[error] |2366137476@[IP]~2o|gen_listener:929(<0.2607.0>) CRASH in handle_event {{badmatch,<<"noop">>},[{stepswitch_bridge,handle_event,2,[{file,"src/stepswitch_bridge.erl"},{line,196}]},{gen_listener,callback_handle_event,4,[{file,"src/gen_listener.erl"},{line,943}]},{gen_listener,callback_handle_event,3,[{file,"src/gen_listener.erl"},{line,907}]},{gen_listener,distribute_event,3,[{file,"src/gen_listener.erl"},{line,825}]},{gen_listener,handle_info,2,[{file,"src/gen_listener.erl"},{line,645}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

I'm on the latest stable release, installed on a single machine (according to the powerpbx guide).

Sorry for hijacking, any help is appreciated.

**Comment by jamesaimonetti** [comment]
@TheEvilCoder42 you can chat about your issues on the [forums](https://forums.2600hz.com/forums/) or file a ticket on [JIRA](https://tickets.2600hz.com). You can run through the [official install guide](https://docs.2600hz.com/sysadmin/doc/install/install_via_centos7/) as well to see if you missed a step.

**Comment by TheEvilCoder42** [comment]
@jamesaimonetti I will open a thread in the forum then. Followed every step listed in the install guide.

**Comment by jamesaimonetti** [comment]
@sergey-safarov can you rebase/update this branch as well? Trying to get these PRs cleaned up and merged/closed as necessary. Thanks and sorry for the delay

**Pull request closed without merging**
