### PR TITLE
Voicemail Fast Forward and Rewind - Rebased on 4.3

### PR DESCRIPTION
**Pull request by noahmehl**
This is a back ported version of the recently merged: https://github.com/2600hz/kazoo/pull/5662

### CODE REVIEW

**Comment by lazedo** [comment]
@noahmehl this can't be merged into 4.3 until full support for latest freeswitch 1.8+ is in place

**Comment by noahmehl** [comment]
@lazedo it’s an opt-in and non breaking feature. We are self deploying the fix into freeswitch 1.6, but even if one didn’t the feature would just do nothing...

**Comment by lazedo** [comment]
@noahmehl true but, that would mean that we support it which we can't until full support for latest freeswitch 1.8+ is in place

**Comment by noahmehl** [comment]
@lazedo what would it take to distribute the patched mod_http_cache?

**Comment by noahmehl** [comment]
Also, it looks like our Monster-UI changes (to master) were merged into 4.3.  So Monster-UI for SmartPBX now shows "Enable fast-forward and rewind?" as an option for voicemail boxes.

**Comment by k-anderson** [comment]
@noahmehl howdy! ya the merge of the feature in 4.3 SmartPBX was a mistake, should NOT have happened until this was accepted and the team was unaware that it wasn't existing functionality.

We will need to revert the commit on SmartPBX 4.3 until this resolved.  Since the master PR is already accepted then the corresponding master SmartPBX is fine.

Sorry for the confusion!

**Comment by noahmehl** [comment]
@k-anderson I was mostly just alerting you, as I figured it was not intended.  But since I have your attention, can we consider the following:

1. Distributing a patched mod_http_cache
2. Open a PR for FreeSWITCH 1.6.x and asking them to merge it

Any help on this would be amazing.

Thanks!

**Comment by k-anderson** [comment]
@noahmehl I am open to that approach, if you can reference the FS PR we can work with them to get it accepted as well as building a patched version for the meantime.

Thanks!

**Comment by noahmehl** [comment]
@k-anderson done: https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1750/overview

BTW, it only takes: git cherry-pick 15c4647c8cf193f2188d1e3548a13a0ad720e710 in v1.6 branch

**Comment by noahmehl** [comment]
@k-anderson FS has declined my PR: https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1750/overview. Can you talk to them?  Or can we distribute a patched mod_http_cache rpm?

**Comment by noahmehl** [comment]
@k-anderson or @lazedo, anything we can do here?

**Comment by lazedo** [comment]
@noahmehl for start, you can rebase due to conflicts.
we are testing a build for 4.x/5.x , `no ETA`

**Comment by noahmehl** [comment]
@lazedo, rebased....

That being said, it doesn't make much sense to continue rebasing this PR if we're not going to find a way to distribute a patched mod_http_cache.  @k-anderson any way we can help with this?

**Comment by lazedo** [comment]
@noahmehl we will get there, but you already know how to do it, and you run your own infrastructure, right ?

**Comment by lazedo** [comment]
@noahmehl thanks for your patience. i believe we will have staging repo with configs/freeswitch/meta shortly (~2 weeks). we will then deploy to selected servers to fully try the upgrade and make sure nothing weird happens. we've been running freeswitch in some servers with minor problems that were all fixed.

**Comment by noahmehl** [comment]
@lazedo Just wanted to touch base on this :)

**Comment by noahmehl** [comment]
@lazedo did the update to freeswitch for 4.3 happen?

**Comment by lazedo** [comment]
@noahmehl yes, kazoo-freeswitch is now 4.3.8 which includes new freeswitch

**Comment by noahmehl** [comment]
@lazedo If I rebased this, can we merge it?

**Comment by lazedo** [comment]
@noahmehl i'm ok with that but will defer to @k-anderson and @jamesaimonetti

**Comment by noahmehl** [comment]
@lazedo @k-anderson @jamesaimonetti, this has been rebased.  This is already in master, and the only blocking item I was aware of was Freeswitch getting the bug fix for seek with playback from http_cache.

**Comment by jamesaimonetti** [comment]
Merged!

**Pull request closed without merging**
