### PR TITLE
When set transcribe, then force used wav media_extension

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by lazedo** [comment]
@sergey-safarov as mentioned before, the changes to cf_voicemail are not desired. the changes to cb_vmboxes are ok (minor spelling) but they should be `opt-in` and the extension should be configurable and not static `wav`, you can use the same configuration field for opt-in and extension, `value` /= `undefined` => `opt-in`

**Comment by sergey-safarov** [comment]
Thanks Luis @lazedo 
`cf_voicemail` changes is reverted.
transcribe extension check also now optional and configurable.

**Comment by lazedo** [comment]
@sergey-safarov thanks, can you please squash your commits ? thanks

**Comment by sergey-safarov** [comment]
@lazedo commits is squashed

**Pull request merged**
