### PR TITLE
no need to filter as from_list already does it

### PR DESCRIPTION
**Pull request by sergey-safarov**
Related to https://github.com/2600hz/kazoo-configs-freeswitch/pull/3

### CODE REVIEW

**Comment by lazedo** [comment]
Is there a reason for this?

**Comment by sergey-safarov** [comment]
Props filter changes done only to allow pass `rtcp_mux` to freeswitch.
Now such changes is no more required.

**Comment by lazedo** [comment]
What if we want to pass false?

**Comment by sergey-safarov** [comment]
Then 'false' value is filtered at `props:filter` and `rtcp_mux` will be disabled by FS global var.

**Comment by lazedo** [comment]
'False' is not filtered by filter_undefined, I would leave this as is or even change it to from_list since it already does a filter_undefined

**Pull request merged**
