### PR TITLE
KAZOO-4797: set quantity to charged seconds (per-minute-voip ledgers doc: rounded billing seconds)

### PR DESCRIPTION
**Pull request by onnet**
separated from https://github.com/2600hz/kazoo/pull/1951

### CODE REVIEW

**Comment by onnet** [comment]
@lazedo Why?  I stepped back at the original one.

**Comment by lazedo** [comment]
@onnet i explained in the other pr why. lets make this pr only for calculations and the other for Rate-Description.

after digging up a little with this, i think that calculations should be into wht_util.
so.., i made this commit here https://github.com/2600hz/kazoo/commit/7a5bbc27fd9e4788a473c19f9572ccb937e053ea
can you pull that commit into pr and test it ?

it moves the calculation to wht_util and jonny5 just uses it.

i tried to edit the pr and add the commit my self, but i'm a noob with git, so it went into another place. sorry for this extra step and thank you.

**Comment by onnet** [comment]
@lazedo  https://github.com/2600hz/kazoo/commit/7a5bbc27fd9e4788a473c19f9572ccb937e053ea pulled and squashed 
Works for me.

**Comment by lazedo** [comment]
@onnet great. please rebase to have it merged.

**Comment by lazedo** [comment]
@onnet hey, can you rename your commit ?
you can use "git rebase -i HEAD~1" and choose "reword".
use a descriptive message in the commit. `forgotten commit` is not useful for future reference.
i create KAZOO-4797 to reflect this work. use "KAZOO-4797 set quantity to charged seconds" (or something like this) as the message in the commit.

**Comment by lazedo** [comment]
@onnet awesome! thanks.

**Pull request merged**
