### PR TITLE
[KAZOO-5359] Allow manual presence to be set for user or device through crossbar

### PR DESCRIPTION
**Pull request by kalda341**

### CODE REVIEW

**Comment by lazedo** [comment]
@kalda341 why did made it as a path token and not extend the already existing post ? presently post does reset but could be extended.

**Comment by kalda341** [comment]
The reset style endpoint like an odd way of doing it as there would never be any other data in the body. Additionally, you would need to prevent the case where reset and the state is set. This follows the pattern in cb_port_requests. IMO the reset should work in the same way, but I didn't want to create any breaking changes.

**Comment by lazedo** [comment]
we're moving away from that pattern. check the channels api

**Comment by kalda341** [comment]
I've updated the code to be more like cb_channels.

**Pull request merged**
