### PR TITLE
Russian system_media prompts 

### PR DESCRIPTION
**Pull request by Dinkor**
Russian prompts
Lack some prompts, they will be added later.

PS: where to put FreeSwitch sound files (from dir /usr/share/freeswitch/sounds/ru/RU)?

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
w00t!

**Comment by Dinkor** [comment]
So what about files from /usr/share/freeswitch/sounds/ru/RU (digits, time, ... )?
They recorded with same voice.

**Comment by jamesaimonetti** [comment]
You'll have to submit those to the FreeSWITCH project I think. Maybe @k-anderson can weigh in on including them in our RPM?

**Comment by Dinkor** [comment]
Which branch i have to clone from kazoo-freeswitch for making pool request?
We always instal freeswitch from repos.2600hz.com

**Comment by jamesaimonetti** [comment]
Make a pull request against https://github.com/2600hz/kazoo-prompts

That should suffice, I believe!

**Pull request merged**
