### PR TITLE
send only updated ccvs

### PR DESCRIPTION
**Pull request by lazedo**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Hmm, I would like to see some tests:
1. Empty list updated with empty list -> nothing to send
2. Empty list updated with `[{K,V}]` -> send `[{K, V}]`
3. `[{K,V}]` updated with `[]` -> nothing to send
4, `[{K, V}]` updated with `[{K1, V1}]` -> send `[{K1, V1}]`
5. `[{K, V}]` updated with `[{K, V1}]` -> send `[{K, V1}]`

Maybe others?

**Comment by lazedo** [comment]
@jamesaimonetti maybe i'm wrong but the `--` handles that
```
(simple-01@dev-01.90e9.com)3> Props = [{k1, v1}].
[{k1,v1}]
(simple-01@dev-01.90e9.com)4> Props -- [{k1, v1}].
[]
(simple-01@dev-01.90e9.com)5> Props -- [{k1, v2}]. 
[{k1,v1}]
(simple-01@dev-01.90e9.com)6> [{k1, v2}] -- Props.
[{k1,v2}]
(simple-01@dev-01.90e9.com)7> [{k1, v1}] -- Props. 
[]
(simple-01@dev-01.90e9.com)8> [{k1, v1}] -- [].   
[{k1,v1}]
(simple-01@dev-01.90e9.com)9> [] -- Props.        
[]
```

and `kapps_call_command:set`  handles empty list

**Comment by jamesaimonetti** [comment]
@lazedo was just looking for proof :)

**Comment by jamesaimonetti** [comment]
@lazedo added a unit test capturing your shell session above.

**Comment by lazedo** [comment]
@jamesaimonetti thank you, thank you, thank you :)

**Pull request merged**
