### PR TITLE
KAZOO-4303: cf_endpoint: fixed getting account document

### PR DESCRIPTION
**Pull request by siplabs**

### CODE REVIEW

**Comment by lazedo** [comment]
@siplabs following up the call we had today, i believe that you are trying to solve an issue caused by an endpoint not having the pvt_account_id field. can you post your endpoint JObj and determine why it doesn't have this field ?

**Comment by siplabs** [comment]
It's user document.
So it goes to
```erlang
merge_attributes(Keys, 'undefined', 'undefined', Doc).
```
After that it sets `Endpoint` to `wh_json:new()` and cannot get `account_id/db` from empty json document.

In this patch account document is loaded and passed to `merge_attributes/4` without trying to guess "where I can find account_db"?

**Comment by siplabs** [comment]
@lazedo 
Can you take a look in `cb_clicktocall`? In click-to-call case CID also will not be set up propertly.
It provides document with type `clicktocall`... So it can't get to `merge_attributes/4`.

**Comment by lazedo** [comment]
@siplabs fixed with commit https://github.com/2600hz/kazoo/commit/4e3c370276d84e7a27e580444ad6a473f51910db 
for `cb_clicktocall` check PR https://github.com/2600hz/kazoo/pull/1381

**Pull request closed without merging**
