### PR TITLE
HELP-34176: from_iso_week fails some years due to incorrect first ISO…

### PR DESCRIPTION
**Pull request by k-anderson**
… 8601 week calculation

### CODE REVIEW

**Comment by sergey-safarov** [comment]
Tested on my test host, PR resolves current issue.

**Comment by k-anderson** [comment]
@sergey-safarov Thanks! I appreciate you letting us know, its good to get confirmation as this is going to need to get built quickly for everyone!

**Comment by noahmehl** [comment]
Hey, is there any chance of this being back ported to 3.22?

**Comment by jamesaimonetti** [comment]
@noahmehl the forum post has [3.22 patch instructions](https://forums.2600hz.com/forums/topic/9529-temporal-route-rule-applies-in-the-future/?tab=comments#comment-52063).

**Pull request merged**
