### PR TITLE
Fix /dev/null being replaced by log rotation

### PR DESCRIPTION
**Pull request by kalda341**

### CODE REVIEW

**Comment by lazedo** [comment]
@kalda341 why do you want to change this ? `data_lager_event` needs to be registered

**Comment by kalda341** [comment]
@lazedo when run with scripts/dev-start-apps.sh /dev/null is rotated, meaning it is replaced with an empty file.

**Comment by lazedo** [comment]
@kalda341 cannot reproduce this. what's your env ? docker ?
i've seen a problem with docker permissions, but the fix was
``` 
{extra_sinks, [{data_lager_event,[]}
                      ]}
````

**Comment by kalda341** [comment]
This occurs on CentOS 7 when `scripts/dev-start-apps.sh` is used to start Kazoo (as root).
After a while /dev/null is replaced with an empty file.

Your docker fix looks like it would solve the problem. Is there any reason for the file backend to `/dev/null`?

**Comment by lazedo** [comment]
i believe that initially we thought that `{handlers, [{lager_file_backend, ..` needed to be configured but didn't want to actually log anything if tracing was not up. can you try the suggested fix to see if it works for you ?
i see it more like a log rotation issue in lager

**Comment by kalda341** [comment]
@lazedo Your docker fix works. I've updated the PR.

**Comment by lazedo** [comment]
@kalda341 thanks

**Pull request merged**
