### PR TITLE
fix warning of unhandled account ID

### PR DESCRIPTION
**Pull request by fenollp**
@lazedo I get a warning every time a number db is created because revise_views tries to convert NumberDb to an account ID (format_account_id fails & returns NumberDb).

Should revise_views really take an account ID? What do you think should be done here?

### CODE REVIEW

**Comment by lazedo** [comment]
@fenollp where do you see that conversion happening ? i don't see revise_views doing any conversion

**Comment by lazedo** [comment]
@fenollp i see where the problem is. i'll add a commit to this branch. you should actually see the warning everytime a number is saved because kzs_publish:publish_doc tries to get account_id from DbName.

**Comment by lazedo** [comment]
@fenollp check if this is what you're looking for.

**Comment by fenollp** [comment]
@lazedo yes this works great. Thanks!

**Pull request merged**
