### PR TITLE
Apply tidier --cases --straighten to files in core dir

### PR DESCRIPTION
**Pull request by kostis**
I was asked to whether it's possible to run tidier on kazoo's code base.
This is the result of applying two of the most basic tidier transformations on the `core` dir of `kazoo`.
The transformations are basic code simplifications and they are non-controversial.

PS. If you like them, there will be more...

### CODE REVIEW

**Comment by lazedo** [comment]
@kostis thanks for this, imho the changed code makes it harder to read.

**Comment by kostis** [comment]
@lazedo : can you give me one good reason why having unused variables makes the code easier to read?

**Comment by fenollp** [comment]
I'm ok with it! I'm also interested in making tidier part of CI.

**Comment by jamhed** [comment]
@fenollp I'm the one who asked :) And I also interested to make it a part of CI.

**Comment by jamesaimonetti** [comment]
Agreed with @fenollp and @jamhed on integrating tidier and that I am okay with the changes. I wasn't aware the 'of' wasn't required and agree with @kostis in this case that the code doesn't suffer in readability. I look forward to tidier's other suggestions.

Side-note: @kostis - Tidier's [website](http://tidier.softlab.ntua.gr:20000/tidier/getstarted) crashes for me:

```erlang
ERROR erlang  code  crashed:
 File: appmod:0
Reason: {undef,
            [{erlyweb,out,
                 [{arg,#Port<0.1092>,
                      {{50,139,13,141},50978},
                      {headers,"keep-alive",
                          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                          "tidier.softlab.ntua.gr:20000",undefined,undefined,
                          undefined,undefined,undefined,undefined,
                          "http://tidier.softlab.ntua.gr:20000/",
                          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36",
                          undefined,[],undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,
                          [{http_header,0,"Dnt",undefined,"1"},
                           {http_header,11,'Accept-Language',undefined,
                               "en-US,en;q=0.8,fr;q=0.6"},
                           {http_header,10,'Accept-Encoding',undefined,
                               "gzip, deflate, sdch"},
                           {http_header,0,"Upgrade-Insecure-Requests",
                               undefined,"1"}]},
                      {http_request,'GET',
                          {abs_path,"/tidier/getstarted"},
                          {1,1}},
                      undefined,"/tidier/getstarted",undefined,"getstarted",
                      "/home/ethan/apps/tidier/www","/",
                      "/home/ethan/apps/tidier/www/tidier/getstarted",
                      undefined,undefined,<0.523.0>,
                      [{"appname","tidier"}],
                      "/","/","/getstarted"}]},
             {yaws_server,deliver_dyn_part,8},
             {yaws_server,aloop,3},
             {yaws_server,acceptor0,2},
             {proc_lib,init_p,5}]}
Req: {http_request,'GET',{abs_path,"/tidier/getstarted"},{1,1}}
```

**Comment by fenollp** [comment]
@kostis Hey this missed [at least one case](https://github.com/2600hz/kazoo/blob/master/core/kazoo_number_manager/src/converters/knm_converter_regex.erl#L164-L170), is this normal?

**Comment by kostis** [comment]
Yes, it's normal, because I was lazy and did not even bother to look in the directory structure of the project.  I simply run tidier with the following command:
<pre>tidier --cases --straighten core/*/src/*.erl</pre>
but apparently I need to also include sub-directories :(
<pre>tidier --cases --straighten core/*/src/*/*.erl</pre>

Doing this, I get:
<pre>
core/kazoo_attachments/src/aws/kz_aws_xml.erl:112: simplifying a case expression with boolean clauses
core/kazoo_attachments/src/aws/kz_aws_xml.erl:111: suggesting a case expression transformation
core/kazoo_number_manager/src/converters/knm_converter_regex.erl:148: suggesting a try expression straightening.
core/kazoo_number_manager/src/converters/knm_converter_regex.erl:162: suggesting a try expression straightening.
core/kazoo_number_manager/src/providers/knm_dash_e911.erl:88: simplifying a case expression with boolean clauses
core/kazoo_number_manager/src/providers/knm_dash_e911.erl:87: suggesting a case expression transformation
core/kazoo_number_manager/src/providers/knm_vitelity_e911.erl:71: simplifying a case expression with boolean clauses
core/kazoo_number_manager/src/providers/knm_vitelity_e911.erl:70: suggesting a case expression transformation
core/kazoo_services/src/bookkeepers/kz_bookkeeper_braintree.erl:623: suggesting a try expression straightening.</pre>

You guys make me work hard -- I do not want to do that, I am lazy :)

**Comment by kostis** [comment]
OK, part 2 is here: https://github.com/2600hz/kazoo/pull/2136

**Comment by jamhed** [comment]
@kostis, we can do it ourselves instead of you if you give access to the tool :)

**Pull request merged**
