### PR TITLE
Csv fix

### PR DESCRIPTION
**Pull request by powerpbx**
This allows empty csv columns when using:

Prefix, ISO, Desc, Surcharge, InternalRate, Rate
Prefix, ISO, Desc, InternalSurcharge, Surcharge, InternalRate, Rate
Prefix, ISO, Desc, InternalSurcharge, Surcharge, Internal_rate, Rate, Routes, RateIncrement, RateMinimum, Direction

### CODE REVIEW

**Comment by lazedo** [comment]
@powerpbx thank you for your contribution, however, as @jamesaimonetti mentioned in https://github.com/2600hz/kazoo/pull/3218 , there's ongoing work where i believe these changes won't fit.

**Comment by powerpbx** [comment]
I had read that.  I am not sure what is being changed or how.  I thought this might raise awareness, otherwise the same limitation might still be there.

**Comment by fenollp** [comment]
@jamesaimonetti ping

**Comment by jamesaimonetti** [comment]
Just echoing what I said in #3218 that I believe this has been addressed and to try it and let us know if things aren't working.

**Pull request closed without merging**
