### PR TITLE
cccp update for 4.0

### PR DESCRIPTION
**Pull request by onnet**
Unfortunately I wasn't able to divide these changes into several steps, 'cause it evolved in time and interconnected. Tested on my single node 4.0 (master).

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Hi @onnet it looks like there's some trailing whitespace in cccp_util.erl and a couple dialyzer complaints (see CircleCI's output for details).

**Comment by onnet** [comment]
Hi @jamesaimonetti  Yep, oh those specs.. :)

**Comment by jamesaimonetti** [comment]
@onnet this latest failure is a bit of an annoyance, but `%` should be for comments at the end of a line while `%%` should be whole-line comments.

Even better, though, is to remove dead code/specs!

**Comment by onnet** [comment]
@jamesaimonetti 
So, do you have any idea of how to get rid of this 'annoyance'?

**Pull request merged**
