### PR TITLE
PISTON-1038: add unix_timestamp_micro to CDR payloads

### PR DESCRIPTION
**Pull request by danielfinke**
Useful for sorting CDR listings so that inbound & outbound legs for each call always show up in the same order (inbound first, outbound next). I'm sure there are other uses.

### CODE REVIEW

**Comment by danielfinke** [comment]
The eunit failure looks unrelated to the contents of this PR.

**Comment by lazedo** [comment]
@danielfinke rebase needed

**Comment by danielfinke** [comment]
@lazedo I'm not familiar with the particular error message I got from the failed `docs` CircleCI job. Do you know what needs to be changed there?

**Comment by lazedo** [comment]
@danielfinke Hi, asking @jamesaimonetti and @icehess help here. probably related to the changes in the view

**Comment by lazedo** [comment]
@danielfinke looks related to how `couchjs` validates the views. we'll try to figure out an alternative to this. thanks.

**Pull request merged**
