### PR TITLE
KAZOO-3179: As an API consumer, I would like to get a list of objects re...

### PR DESCRIPTION
**Pull request by k-anderson**
...lated to prompt language files so that I can see metadata about the prompt language files

### CODE REVIEW

**Comment by k-anderson** [comment]
@macpie I found this this code while cleaning the old branches, the Jira ticket is marked closed (but not wont-fix).  If we accept this change it should only impact v2 APIs.  You should also make sure the front-end is updated (or not impacted).

**Comment by macpie** [comment]
You mean you want me to add that only to v2 ?

**Comment by jamesaimonetti** [comment]
@k-anderson I don't think that's necessary, as this is prompts-only stuff, which wasn't introduced until v2 anyway. No one using /v1 would have been using the prompts stuff anyway.

@macpie just make sure there's a ticket filed with the UI to handle the new format of the response for prompts.

**Comment by macpie** [comment]
ok

**Pull request merged**
