### PR TITLE
process /account alias as /accounts/{AUTH_ACCOUNT_ID}

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@lazedo I tried to move the authenticate earlier, but it relies on req nouns existing. At this point, it feels too invasive to try to get that untangled. Worth the effort or leave it as is until we want to add `/user`?

**Comment by jamesaimonetti** [comment]
@lazedo just kidding, i think i fixed it.

**Comment by lazedo** [comment]
@jamesaimonetti awesome! just one comment,  no need to validate the token twice (early and authenticate)

**Comment by jamesaimonetti** [comment]
@lazedo rebased

**Pull request merged**
