### PR TITLE
Revert "metaflow.callflow: should "id" field be the mandatory one?"

### PR DESCRIPTION
**Pull request by onnet**
Reverts 2600hz/kazoo#3503 in order to satisfy circleci

### CODE REVIEW

**Comment by lazedo** [comment]
@onnet  you need to run `make apis` and could you please squash into one commit ? thanks

**Comment by lazedo** [comment]
@onnet  circleci is not working properly for external PRs, not sure why. @fenollp ?
this is what we see if we merge
```
Unstaged changes!
 M applications/crossbar/priv/api/swagger.json
diff --git a/applications/crossbar/priv/api/swagger.json b/applications/crossbar/priv/api/swagger.json
index aea77ed66..4ae01478f 100644
--- a/applications/crossbar/priv/api/swagger.json
+++ b/applications/crossbar/priv/api/swagger.json
@@ -5398,9 +5398,6 @@
                     "type": "string"
                 }
             },
-            "required": [
-                "id"
-            ],
             "type": "object"
         },
         "metaflow.hangup": {
Maybe try `make apis` and see if that fixes anything ;)
```

**Comment by onnet** [comment]
@lazedo sorry for the delay, will give 'make apis' a try soon. just got some other stuff to do suddenly..

**Comment by lazedo** [comment]
@onnet closing this in favor of #3515

**Pull request closed without merging**
