### PR TITLE
qf-osx_compile: fix openssl and missing symboles errors

### PR DESCRIPTION
**Pull request by icehess**

### CODE REVIEW

**Comment by lazedo** [comment]
@icehess `21:04:19.071 [error] |0000000000|Undefined:Undefined (<0.4087.0>) kz_auth_rsa_drv: Error loading "kz_auth_rsa_drv": "undefined symbol: ei_decode_version"`
this was why i switched to rebar

**Comment by icehess** [comment]
@lazedo are you testing on linux?

**Comment by lazedo** [comment]
its circleci output

**Comment by fenollp** [comment]
@icehess note Travis CI can build for OSX (as well as Circle, but I believe Travis has a free OSX CI plan) if you wanna get into that.

**Comment by icehess** [comment]
now I broke it again

**Pull request merged**
