### PR TITLE
Term conversion

### PR DESCRIPTION
**Pull request by jamesaimonetti**
Breaks out term conversion into `kz_term.erl`, move binary-handling functionality into `kz_binary.erl` and adds a script to help with the migration so others can migrate their code too. This is basically chopping up #1892 into more manageable pull requests (hopefully).

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@jamhed any insight into MakeBusy here? Seems gateways are timing out but unsure why (and kazoo.log is *huge*).

**Comment by jamesaimonetti** [comment]
@lazedo this is ready

**Comment by lazedo** [comment]
@jamesaimonetti rebase needed

**Comment by jamesaimonetti** [comment]
@lazedo ready

**Pull request merged**
