### PR TITLE
ensure kazoo_bindings is up

### PR DESCRIPTION
**Pull request by lazedo**
orelse it will fail with ast

### CODE REVIEW

**Comment by lazedo** [comment]
@jamesaimonetti i think this fixes the kzs_plan reload. there's still an error related to the attachments change

**Comment by lazedo** [comment]
@jamesaimonetti added sleep after update & cleanup and its fine. makebusy failure is expected because of base branch

**Comment by lazedo** [comment]
@jamesaimonetti finally!
```
15:58:55.851 [debug] |0000000000|kzs_plan:500 (<0.5631.3>) module kzs_plan reloaded
15:58:55.851 [debug] |undefined|kzs_plan:490 (<0.5632.3>) initializing plans
15:58:55.851 [debug] |undefined|kzs_plan:321 (<0.5632.3>) caching dataplan key <<"system">>
15:58:55.851 [debug] |00000000000|kazoo_bindings:508 (<0.2976.0>) trying to flush kzs_plan
15:58:55.851 [debug] |00000000000|kazoo_bindings:527 (<0.2976.0>) no more responders, removing kapi.conf.kazoo_data_plan_cache.system_data.storage.doc_created.*
15:58:55.852 [info] |0000000000|pqc_cb_storage:220 (<0.6125.0>) hotload kzs_plan: <0.2976.0> : ok
15:58:55.853 [debug] |00000000000|kazoo_bindings:527 (<0.2976.0>) no more responders, removing kapi.conf.kazoo_data_plan_cache.system_data.storage.doc_deleted.*
15:58:55.855 [debug] |undefined|kzs_plan:321 (<0.5632.3>) caching dataplan key <<"2051a7c2ff53e90a3c7b72e4e3578902">>
```

**Comment by jamesaimonetti** [comment]
Merged into #6490

**Pull request closed without merging**
