### PR TITLE
KAZOO-5302: Updated tollfree regex

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by fenollp** [comment]
I'd say that regexp could be extended to support all of what's in https://github.com/2600hz/kazoo/blob/0def604c6f8d142bac2e4a2d076c48130fa8adef/core/kazoo_number_manager/src/knm.hrl#L15-L31 (that's from wikipedia).
What do you think @lazedo ?

**Comment by fenollp** [comment]
Once done, run `make apis`. That's what's bothering circleci.

**Comment by sergey-safarov** [comment]
Regex extended

**Comment by sergey-safarov** [comment]
make apis results here
http://pastebin.com/dT8zcq3S

**Comment by fenollp** [comment]
Thanks! Let me try to merge this.

**Pull request merged**
