### PR TITLE
KAZOO-3353:  ability to set notify_email_address (array of emails) on a ...

### PR DESCRIPTION
**Pull request by macpie**
...voicemail box, so that I can notify multiple persons when this voicemail box receives a message

### CODE REVIEW

**Comment by onnet** [comment]
Hi guys!

Please take a look at lines 151 and 158.
You've got variable To (binary) as a function argument at line 151:
build_and_send_email(TxtBody, HTMLBody, Subject, To, Props, {RespQ, MsgId})

And at line 158 trying to bind it again as a List:
    To = props:get_value(<<"email_address">>, Props),

This provides crash:

Feb 21 14:17:00 kz527 2600hz[1738]: |0000000000|Undefined:Undefined (<0.4279.0>) CRASH REPORT Process <0.4279.0> with 0 neighbours crashed with reason: no match of right hand value [<<"iam@onnet.su">>] in notify_voicemail_to_email:build_and_send_email/6 line 158

Feb 21 14:17:30 kz527 2600hz[1738]: |56cdc345-951fd7be@192.168.111.204|cf_voicemail:1062 (<0.4076.0>) timed out waiting for resp
Feb 21 14:17:30 kz527 2600hz[1738]: |56cdc345-951fd7be@192.168.111.204|cf_exe:642 (<0.4076.0>) action cf_voicemail died unexpectedly (error): {badmatch,{error,"Proplist failed validation for voicemail"}}
Feb 21 14:17:30 kz527 2600hz[1738]: |0000000000|Undefined:Undefined (emulator) Error in process <0.4076.0> on node 'whistle_apps@kz527.onnet.su' with exit value: {{nocatch,{badmatch,{error,"Proplist failed validation for voicemail"}}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,644}]}]}#012#012
Feb 21 14:17:30 kz527 2600hz[1738]: |56cdc345-951fd7be@192.168.111.204|cf_exe:452 (<0.4063.0>) action cf_voicemail died unexpectedly: {{nocatch,{badmatch,{error,"Proplist failed validation for voicemail"}}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,644}]}]}

Regards,
Kirill

**Comment by lazedo** [comment]
Hi Kirill,

fixed with https://github.com/2600hz/kazoo/commit/87a2f17b6269056e9df7e0d5cec8e8c7545e08b3

**Comment by onnet** [comment]
Hi Luis!

Nice to see you!

But still, why do you need this pattern matching in 158 since "To" is already defined in 151?

By the way, there was another problem in provided above logs:
cf_voicemail died unexpectedly (error): {badmatch,{error,"Proplist failed validation for voicemail"}}

It crashes in wapi_notifications.erl over here:
voicemail_saved(Prop) when is_list(Prop) ->
    case voicemail_saved_v(Prop) of
        'true' -> wh_api:build_message(Prop, ?VOICEMAIL_HEADERS, ?OPTIONAL_VOICEMAIL_HEADERS);
        'false' -> {'error', "Proplist failed validation for voicemail 2"}
    end;
voicemail_saved(JObj) -> voicemail_saved(wh_json:to_proplist(JObj)).

Here are debug level logs:

Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|cf_voicemail:1130 (<0.4365.0>) stored voicemail metadata for b2cf3ee131ff7f428fdbab84cc4801ce
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_api:422 (<0.4365.0>) API key 'Event-Name' value '<<"voicemail_new">>' is not '<<"voicemail_saved">>'
Feb 21 15:07:23 kz527 2600hz[9088]: |00000000000|wh_amqp_channel:154 (<0.236.0>) published to configuration(amqp://guest:guest@94.125.5.27:5672) exchange (routing key doc_edited.account%2F33%2Fca%2F3929ed585e0e423eb39e4ffe1452.vmbox.19c55c64abc4ee7b496cea6e70a612a0) via <0.194.0>
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_api:259 (<0.4365.0>) failing API JSON: {"Msg-ID":"ae6acbbf82056616a2fbb942ec0c803c","Event-Name":"voicemail_new","Event-Category":"notification","From-User":"spa525","From-Realm":"office.sip3.onnet.su","To-User":"5555","To-Realm":"office.sip3.onnet.su","Account-DB":"account%2F33%2Fca%2F3929ed585e0e423eb39e4ffe1452","Account-ID":"33ca3929ed585e0e423eb39e4ffe1452","Voicemail-Box":"19c55c64abc4ee7b496cea6e70a612a0","Voicemail-Name":"b2cf3ee131ff7f428fdbab84cc4801ce","Caller-ID-Number":"5511","Caller-ID-Name":"spa525g","Voicemail-Timestamp":63591739643,"Voicemail-Length":4300,"Call-ID":"37c5521f-1f0195ea@192.168.111.204","Server-ID":"undefined","App-Name":"callflow","App-Version":"0.8.2","Node":"whistle_apps@kz527.onnet.su"}
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|cf_exe:642 (<0.4365.0>) action cf_voicemail died unexpectedly (error): {badmatch,{error,"Proplist failed validation for voicemail 2"}}
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:127 (<0.4365.0>) stacktrace:
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: wapi_notifications:publish_voicemail_saved/2 at (916)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: cf_voicemail:publish_voicemail_saved/5 at (1174)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: cf_voicemail:update_mailbox/4 at (1063)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: cf_voicemail:record_voicemail/3 at (432)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: cf_voicemail:handle/2 at (138)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|wh_util:134 (<0.4365.0>) st: cf_exe:-spawn_cf_module/3-fun-1-/4 at (637)
Feb 21 15:07:23 kz527 2600hz[9088]: |37c5521f-1f0195ea@192.168.111.204|cf_exe:452 (<0.4349.0>) action cf_voicemail died unexpectedly: {{nocatch,{badmatch,{error,"Proplist failed validation for voicemail 2"}}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,644}]}]}

Are you aware of it?
Do I need to dig deeper?

Regards,
Kirill

**Comment by lazedo** [comment]
@onnet all fixed now. thanks for reporting

**Comment by onnet** [comment]
Great? 

Thank you Luis.
Do you plan to backport it to 3.19, since changes where these bugs were introduced are olso over there?

Reagrds,
Kirill

**Comment by lazedo** [comment]
@onnet cherry-picked to 3.19. thanks for noticing.

**Pull request merged**
