### PR TITLE
Ensure whole project's exported functions are spec-ed

### PR DESCRIPTION
**Pull request by fenollp**
This adds a compilation flag project-wide: `+warn_missing_spec`.
This means that if a module is missing a `-spec` on an exported function, compilation will now fail.

Help requested on how to fix Dialyzer complaints in CI! but chances are they don't really matter.

Spéciale dédicace à @jamesaimonetti

### CODE REVIEW

**Comment by fenollp** [comment]
This is ready btw

**Comment by lazedo** [comment]
@fenollp circleci failed

**Comment by fenollp** [comment]
> Help requested on how to fix Dialyzer complaints in CI! but chances are they don't really matter.

**Comment by fenollp** [comment]
Closing in favor of https://github.com/2600hz/kazoo/pull/2819

**Pull request closed without merging**
