### PR TITLE
KAZOO-5685-4.1: number db naming

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by k-anderson** [comment]
@jamesaimonetti I want to hold on this PR until we can test the master version fully.

**Comment by jamesaimonetti** [comment]
@k-anderson thoughts on this now?

**Comment by kalda341** [comment]
@jamesaimonetti @icehess This has broken refreshing number databases like "numbers/+9999" as they format to 'undefined'. Noticed in 4.1.52.

**Comment by jamesaimonetti** [comment]
@kalda341 have examples?

```erlang
(pdx-4-1@pdx.2600hz.com)6> knm_util:get_all_number_dbs().
[<<"numbers%2F%2B9999">>]
(pdx-4-1@pdx.2600hz.com)7> [kzs_util:db_classification(Db) || Db <- knm_util:get_all_number_dbs()].
[numbers]
```
Seems okay to me?

**Comment by kalda341** [comment]
When I run:
`
sup kapps_maintenance refresh
`

A bunch of stuff, then when it encounters the first number database with a +:
`
<9880.29158.8> (3491/3515) refreshing database 'numbers/+9999'
Command failed: {'EXIT',{{badmatch,{error,not_found}},[{kazoo_number_manager_maintenance,refresh_numbers_db,1,[{file,"src/kazoo_number_manager_maintenance.erl"},{line,185}]},{kapps_maintenance,refresh,3,[{file,"sr
c/kapps_maintenance.erl"},{line,252}]},{sup,in_kazoo,4,[{file,"src/sup.erl"},{line,93}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,206}]}]}}
`

Sorry, my assumption of how it was failing was incorrect. The real issue is that the + is not being URL encoded. The encoded database is `numbers%2F+9999`, which is incorrect.

**Comment by jamesaimonetti** [comment]
@kalda341 strange, I don't see the crash locally. Can you grab the logs around the crash?

**Comment by kalda341** [comment]
@jamesaimonetti 
The following is for a different server with different databases, but displays the same issue.
I ran `kazoo_number_manager_maintenance refresh_numbers_dbs` instead to get here faster.

I've also removed the database classification errors which arise as we have databases that kzs_util:db_classification doesn't know about.


`
00:02:03.567 [info] |99c83508-6e60-4893-85ab-4caa08342f45|kz_nodes:676 (<0.1228.0>) VM sup_2a35@torontocstqstvygr.conversanthq.com is now connected:
00:02:03.567 [notice] |sup_2a35@torontocstqstvygr.conversanthq.com|sup:92 (<0.12550.3>) sup: kazoo_number_manager_maintenance refresh_numbers_dbs 
00:02:03.665 [debug] |sup_2a35@torontocstqstvygr.conversanthq.com|kazoo_number_manager_maintenance:179 (<0.12550.3>) (105/105) updating number db numbers/+0011
00:02:03.670 [debug] |sup_2a35@torontocstqstvygr.conversanthq.com|kz_datamgr:117 (<0.12550.3>) update db numbers%2F+0011 from CouchDB file: /opt/kazoo/lib/kazoo_number_manager-4.1.52/priv/couchdb/views/numbers.json
00:02:03.677 [debug] |sup_2a35@torontocstqstvygr.conversanthq.com|kz_datamgr:149 (<0.12550.3>) failed to update doc: not_found
00:02:05.594 [info] |c4a5b5c6-0a94-4cce-81da-fd652c89da2b|kz_nodes:669 (<0.1228.0>) VM sup_2a35@torontocstqstvygr.conversanthq.com is no longer connected:
`


In the BigCouch logs I see:
`
[Wed, 17 Jan 2018 00:02:03 GMT] [info] [<0.10218.14>] [3f8d3ee8] 127.0.0.1 127.0.0.1:15984 PUT /numbers%2F+0011/_design/numbers 404 ok 2
`

**Comment by jamesaimonetti** [comment]
Yeah, that's what others are reporting.

What's the diff between `kz_datamgr:db_info()` and `knm_util:get_all_number_dbs()` for you?.

I see:
```erlang
1> kz_datamgr:db_info().
{ok, [..., <<"numbers/+1234">>,<<"numbers/+2999">>,<<"numbers/+9999">>,...]}.
2> knm_util:get_all_number_dbs().
[<<"numbers%2F%2B1234">>,<<"numbers%2F%2B2999">>,
 <<"numbers%2F%2B9999">>]
```

**Comment by jamesaimonetti** [comment]
And my refresh command logs:

```
2018-01-17T00:02:15.481683+00:00 pdx 2600hz[30034]: kazoo_number_manager_maintenance:179 (<0.10770.0>) (3/3) updating number db numbers/+2999
2018-01-17T00:02:15.481872+00:00 pdx 2600hz[30034]: kz_datamgr:117 (<0.10770.0>) update db numbers%2F%2B2999 from CouchDB file: /home/james/local/git/2600hz/kazoo-4.1/scripts/../core/kazoo_number_manager/priv/couchdb/views/numbers.json
```

**Comment by kalda341** [comment]
@jamesaimonetti 

`
{'ok', D} = kz_datamgr:db_info().
[X || X <- D, binary:match(X, <<"numbers">>) =/= 'nomatch'].
`
Output:
`
[<<"numbers/+0011">>,<<"numbers/+0014">>,
 <<"numbers/+0061">>,<<"numbers/+0282">>,<<"numbers/+0800">>,
 <<"numbers/+1000">>,<<"numbers/+1134">>,<<"numbers/+1214">>,
 <<"numbers/+1347">>,<<"numbers/+1408">>,<<"numbers/+1415">>,
 <<"numbers/+1416">>,<<"numbers/+1643">>,<<"numbers/+1669">>,
 <<"numbers/+1888">>,<<"numbers/+1932">>,<<"numbers/+2710">>,
 <<"numbers/+2882">>,<<"numbers/+2884">>,<<"numbers/+3054">>,
 <<"numbers/+3317">>,<<"numbers/+3867">>,<<"numbers/+4025">>,
 <<"numbers/+4413">>,<<"numbers/+4420">>,
 <<"numbers/+448"...>>,<<"numbers/"...>>,<<"numb"...>>,
 <<...>>|...]
`

`
knm_util:get_all_number_dbs().
`
Output:
`
[<<"numbers%2F%2B0011">>,<<"numbers%2F%2B0014">>,
 <<"numbers%2F%2B0061">>,<<"numbers%2F%2B0282">>,
 <<"numbers%2F%2B0800">>,<<"numbers%2F%2B1000">>,
 <<"numbers%2F%2B1134">>,<<"numbers%2F%2B1214">>,
 <<"numbers%2F%2B1347">>,<<"numbers%2F%2B1408">>,
 <<"numbers%2F%2B1415">>,<<"numbers%2F%2B1416">>,
 <<"numbers%2F%2B1643">>,<<"numbers%2F%2B1669">>,
 <<"numbers%2F%2B1888">>,<<"numbers%2F%2B1932">>,
 <<"numbers%2F%2B2710">>,<<"numbers%2F%2B2882">>,
 <<"numbers%2F%2B2884">>,<<"numbers%2F%2B3054">>,
 <<"numbers%2F%2B3317">>,<<"numbers%2F%2B3867">>,
 <<"numbers%2F%2B4025">>,<<"numbers%2F%2B4413">>,
 <<"numbers%2F%2B442"...>>,<<"numbers%2F%2"...>>,
 <<"numbers%"...>>,<<"numb"...>>,<<...>>|...]
`

**Pull request merged**
