### PR TITLE
KAZOO-5832: fixed different device activation_charges for dirty and s…

### PR DESCRIPTION
**Pull request by sergey-safarov**
…ynchronized services

### CODE REVIEW

**Comment by sergey-safarov** [comment]
I not able to see `MakeBusy` errors. Host `docker.2600hz.com:8074` rejects connections
Could you describe what is wrong.

**Comment by lazedo** [comment]
@sergey-safarov you should create the PR for master and then possibly backport. if its something already in master, then you should referenced it as part of the 4.1 PR

**Comment by sergey-safarov** [comment]
Hello Luis (@lazedo)
This because i can not build/test current master on my host.
[PR to master](https://github.com/2600hz/kazoo/pull/4567)

**Comment by sergey-safarov** [comment]
After upgrading erlang form 18 to erlang 19 i can build master.
After some test i found error like.
```
19:59:31.122 debug kz_service_plan.28 found service plan account%2F63%2Ff8%2F14795fd5b8c74aa04ee865c52f73/525d0b46bbb69a64ecd4d384a9ca6d26
19:59:31.125 error kazoo_bindings.692 excepted: error: {badmatch,{error,not_found}}
19:59:31.125 error kz_util.118 stacktrace:
19:59:31.125 error kz_util.125 st: kz_service_plans:get_object_plans/2 at (115)
19:59:31.125 error kz_util.125 st: lists:foldl/3 at (1263)
19:59:31.125 error kz_util.125 st: kz_service_plans:from_service_json/1 at (69)
19:59:31.125 error kz_util.125 st: kz_services:service_plan_json/1 at (647)
19:59:31.125 error kz_util.125 st: cb_apps_util:check_service_plan/1 at (142)
19:59:31.125 error kz_util.125 st: cb_apps_util:allowed_apps/2 at (33)
19:59:31.125 error kz_util.125 st: crossbar_util:load_apps/3 at (755)
19:59:31.125 error kz_util.125 st: crossbar_util:populate_resp/3 at (735)
```

PR will be closed until issue is resolved.

**Pull request closed without merging**
