### PR TITLE
Update users.md to add `password` property

### PR DESCRIPTION
**Pull request by powerpbx**
Not in JSON so it would not be in documentation generated from that.

### CODE REVIEW

**Comment by fenollp** [comment]
Hello!
Could you rebase your PR to latest master & force push please?

**Comment by powerpbx** [comment]
I have now done that.

**Comment by fenollp** [comment]
Okay in order to really add something here you need to update the schema.
For this file the schema is https://github.com/2600hz/kazoo/blob/3e6adafbb4748e00fe3b5582f21f75852a78aa97/applications/crossbar/priv/couchdb/schemas/users.json#L420

Please revert / remove your current commits, then modify that JSON file, then run `make apis` then push whatever files there are to push :)
Easy, right?

**Comment by powerpbx** [comment]
As far as I can tell, password is a special case.  It is not in the schema because you do not save it anywhere in plain text.  So I am pretty sure you do not want it in the schema.

**Comment by fenollp** [comment]
Why do you want to document this field? How have you been using it?

**Comment by powerpbx** [comment]
To create/update accounts via API.

**Comment by fenollp** [comment]
Okay so after discussion with the team this should be documented the way I described.
If you don't want to anymore, close this & I'll do it myself :)

In any case, please keep reporting things that you use & do not find in the documentation.
We are working on making it better every day :)

**Comment by powerpbx** [comment]
So would this just be a placeholder in the scheme that doesn't do anything other than show up in autogenerated documents?  Is there an example of this somewhere in another scheme?

**Comment by fenollp** [comment]
Hey @powerpbx I had a shot at this: https://github.com/2600hz/kazoo/pull/3148
Please close your PR if you're okay with mine ;)

**Pull request closed without merging**
