### PR TITLE
removing atom ticking policy

### PR DESCRIPTION
**Pull request by lazedo**
if you agree, add `plus`
don't merge yet

### CODE REVIEW

**Comment by jamhed** [comment]
How can I add +100500?

**Comment by mark2600** [comment]
I guess before voting I should have clarified.

Are we INVERTING this policy, or REMOVING it ?

**Comment by lazedo** [comment]
removing the policy, NOT inverting it.
you can still add the tickies :)

**Comment by jamesaimonetti** [comment]
@lazedo looks like its 6 to 8 in favor of keeping tickies! Time to close and resume yelling at PRs without them!

**Comment by fenollp** [comment]
Can we up the ante a bit?
How about: if we keep the policy that REQUIRES tickies then let's build a tool that adds them for us?

**Comment by lazedo** [comment]
@jamesaimonetti start yelling :)
@fenollp make the tool

**Pull request closed without merging**
