### PR TITLE
J5 trunks use separate white black lists for inbound/outbound.

### PR DESCRIPTION
**Pull request by cando-1p**
Support for having separate inbound and outbound white and black lists to define J5 trunks.
Third (pull request) times a charm. :)

See discussion that lead to current proposed code in https://github.com/2600hz/kazoo/pull/602.
Also this is the first small step in the leadup to https://2600hz.atlassian.net/browse/KAZOO-3038
It is design is laid out in the google doc https://docs.google.com/document/d/19JlWKIe53q2e2MQIhsF-ohTkGcaYx6AHwcMHU_AquVo/edit?usp=sharing

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@cando-1p haven't forgotten about this! Just need to find some time to pull it down locally and play with it. Hoping to merge or give feedback today or tomorrow. Sorry for the delay and thanks for the patience.

**Comment by cando-1p** [comment]
Not a problem. Actually I had cause to push on to the next step of
implementing overrides as I discussed in
https://docs.google.com/document/d/19JlWKIe53q2e2MQIhsF-ohTkGcaYx6AHwcMHU_AquVo/edit?usp=sharing
 Kazoo Jira ticket 3038 <https://2600hz.atlassian.net/browse/KAZOO-3038>.
I also reworked the nested case statement into functions. More
erlang/2600hz style. :)
I hope to do a pull on it today.

**Comment by k-anderson** [comment]
Sorry that this has remained so long, we are trying to catch up on these.  It just takes a while to really understand and play with the changes.  I am trying to set aside time next week to do this, so please forgive us but know that we do intend to accept it!

**Comment by cando-1p** [comment]
In the interim, I've found and fixed some big bugs in it. But haven't had
time to apply them against master and do another pull request. I'll be
trying to get that hopefully in the next few weeks.

**Comment by k-anderson** [comment]
@cando-1p Howdy, ok I will wait then for the bug fixes to get merged into the PR before I test it ;)
Just let me know when you are ready!

**Comment by fenollp** [comment]
@cando-1p Any update on this?

**Comment by k-anderson** [comment]
@cando-1p These changes appear to be covered in https://github.com/2600hz/kazoo/pull/749/files

**Pull request closed without merging**
