### PR TITLE
check code style

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Woops, just noticed this check doesn't run properly yet!

> Symbol's function definition is void: cl-mapc

Need to work with Travis' default emacs which should be emacs23 or 22.

**Comment by lazedo** [comment]
i don't agree with this

**Comment by fenollp** [comment]
Travis will not support checking this soon according to https://github.com/travis-ci/travis-ci/issues/6076
Emacs' version is the culprit here.

This PR has to be rethought with one of these possible solutions (in no special order):
* https://github.com/tsloughter/erl_tidy
* https://github.com/jimenezrick/vimerl/blob/master/indent/erlang_indent.erl
* https://github.com/mbucc/erlfmt
* https://github.com/ebengt/erlang_stdin_formatter

Validation criteria:
* MUST be a compile time script
* MUST `style(style(Codebase)) === style(Codebase)`

An proper ticket should be written. Will get back to this at some point.

**Comment by k-anderson** [comment]
@fenollp rebase me!

**Comment by fenollp** [comment]
@k-anderson so this works but needs a freeze of all other PRs otherwise last commit will always need to be redone :)

**Pull request merged**
