### PR TITLE
Added feature to configure rtcp_mux for sip calls via resources gateway

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by sergey-safarov** [comment]
@lazedo `rtcp_mux` channel variable is passed to ecallmgr correctly. Double checked.

**Comment by k-anderson** [comment]
@lazedo it was already in the special channel vars
@sergey-safarov Howdy, nice add! I had some formatting tweaks so I have opened an alternative #3899 let me know what you think! (Also, I have not had a chance to test it yet...)

**Comment by lazedo** [comment]
@k-anderson i know, i added it :) if you want to change the name, you'll need to change fax_request (at least) but a search on the repo is more safe

**Comment by k-anderson** [comment]
@lazedo ah ;) I search the enter repo (actually all projects) and had no hits for RTCP-Mux with grep... Do you know where?

**Comment by k-anderson** [comment]
@lazedo nm found it, bad grep

**Comment by k-anderson** [comment]
@sergey-safarov Howdy, after some discussion with the team we decided to use this as it was originally submitted!  I will close my PR and accept this.  Thanks!

**Pull request merged**
