### PR TITLE
Gateway strategies

### PR DESCRIPTION
**Pull request by noahmehl**
This is a feature to allow for random gateways in an offnet document.  We have PR'd to 4.3 for the time being until we can develop again for master.

### CODE REVIEW

**Comment by lazedo** [comment]
@noahmehl `until we can develop again for master`. what's blocking you from that ?

**Comment by noahmehl** [comment]
@lazedo we haven't been able to get Kamailio + FS working in master.  Can you confirm the freeswitch and kamailio versions, as well as which branch of their respective kazoo-configs we should be using?

**Comment by lazedo** [comment]
@noahmehl https://forums.2600hz.com/forums/topic/10756-kazoo-master-branch-install/?tab=comments#comment-58413

**Comment by noahmehl** [comment]
Thanks, we'll take a look.

**Comment by noahmehl** [comment]
@lazedo I have tried the steps in the forum post, however, I cannot start kamailio...

**Comment by noahmehl** [comment]
Corresponding master PR: https://github.com/2600hz/kazoo/pull/6246

**Comment by noahmehl** [comment]
@jamesaimonetti The master branch PR has already been merged.

**Comment by jamesaimonetti** [comment]
Merged

**Pull request closed without merging**
