### PR TITLE
Fixed detergent build

### PR DESCRIPTION
**Pull request by sergey-safarov**
repo https://github.com/pap/detergent no more exist

### CODE REVIEW

**Comment by sergey-safarov** [comment]
Code fresh build error related to automatic test in my account and to `4.3` branch in my repo with extra commits.
Really kazoo build properly with this commits.

**Comment by lazedo** [comment]
@sergey-safarov any reason in particular for this repo ? why not use the default which goes back to `https://github.com/devinus/detergent` ? so maybe the change is just to remove the line ?

**Comment by jamesaimonetti** [comment]
I'd rather just remove it and the DTH app - long dead. See #6535

**Comment by jamesaimonetti** [comment]
DTH is moved to kazoo-community and detergent is removed from deps.mk

**Comment by sergey-safarov** [comment]
@lazedo without [this change](https://github.com/devinus/detergent/pull/18/commits/399e363f260751b38b978aa882b9681f395bd496) `make build-release` will fail.

**Pull request closed without merging**
