### PR TITLE
Allow additional teletype notifications w/o modifying existing code

### PR DESCRIPTION
**Pull request by kalda341**
We would like to be able to send our own notifications through teletype, without modifying any existing 2600Hz code. This allows us to achieve this, by defining additional bindings and responders in the system_config.

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
I like this idea and wonder...why not just have it load all teletype templates at startup? Then it will load "default" templates but still allow others to add their own template modules as well.

That's my first impression, anyway. Make it the general loader for all templates, default and custom. Thoughts?

**Comment by kalda341** [comment]
Sounds good to me! What I had in mind too, but thought it might be too drastic a change to be accepted.
Should I develop this further, or leave it with you?

**Comment by kalda341** [comment]
@jamesaimonetti Any updates?

**Comment by jamesaimonetti** [comment]
@kalda341 sorry for the delay, didn't get Github notifications in email! Yes, please refactor to be a general loader of templates.

**Comment by kalda341** [comment]
Functionality improved in https://github.com/2600hz/kazoo/pull/3363

**Pull request closed without merging**
