### PR TITLE
refactor: knm.hrl from include to include_lib

### PR DESCRIPTION
**Pull request by jamhed**

### CODE REVIEW

**Comment by lazedo** [comment]
@jamhed why ?

**Comment by fenollp** [comment]
Yeah knm.hrl is in src/ so that outside apps don't try to include it.

**Comment by jamhed** [comment]
@fenollp okay, I put it back to src, but leave include_lib. Will this work? :)

**Comment by lazedo** [comment]
@jamhed but why are changing this ? what's not working for you to make the change ?

**Comment by jamhed** [comment]
@lazedo, to make sync work, see https://github.com/2600hz/kazoo/pull/1955. It fails to recompile on the fly files with include because it doesn't know where to look for (you need to specify the include path as compiler option), and with include_lib it knows.

**Comment by fenollp** [comment]
No include_lib won't work for things in src. that's the point

**Comment by jamhed** [comment]
@fenollp it will work with src like this: include_lib("kazoo_number_manager/src/knm.hrl").

**Pull request closed without merging**
