### PR TITLE
Let trunkstore live a bit longer

### PR DESCRIPTION
**Pull request by onnet**
A patch as a result of the next conversation: https://groups.google.com/forum/#!topic/2600hz-users/1BmpiqBiMks

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@onnet I think you may need to rebase against latest master to get Circle happy

**Comment by lazedo** [comment]
@onnet hey, can you please rebate ? We had an issue with some deps.

**Comment by onnet** [comment]
@lazedo hi, maybe you mean rebase? :)

**Comment by lazedo** [comment]
@onnet yep, blame my cellphone corrector :)

**Comment by onnet** [comment]
@lazedo rebased today, but it didn't help

**Comment by lazedo** [comment]
@onnet dialyzer issue. don't know why its even checking this file.
```
scanning "applications/trunkstore/ebin/ts_callflow.beam"
warn_matching                 ts_callflow.erl:58: Record construction #ts_callflow_state{amqp_worker::'undefined',call_cost::float()} violates the declared type of field amqp_worker::pid()
```

**Comment by lazedo** [comment]
@onnet maybe changing `pid()` to `api_pid()` here https://github.com/onnet/kazoo/blob/cb2206403827ebe849586a9a908521cff4219a9b/applications/trunkstore/src/ts.hrl#L47

**Comment by onnet** [comment]
@lazedo will give it a try right now...

**Comment by jamesaimonetti** [comment]
Thanks @onnet, merged

**Comment by jamesaimonetti** [comment]
and thanks for appeasing our lord and savior Dialyzer ;)

**Pull request closed without merging**
