### PR TITLE
Validating custom SIP headers in devices

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
I don't recall but can the headers only be "X-" or can they be "P-" as well?

**Comment by jamesaimonetti** [comment]
@lazedo @k-anderson thoughts now?

**Comment by fenollp** [comment]
you need to add anyOf in https://github.com/2600hz/kazoo/blob/master/core/kazoo_ast/src/cb_api_endpoints.erl?utf8=%E2%9C%93#L261 for Swagger to pass.

**Comment by onnet** [comment]
@jamesaimonetti Hi! Just upgraded one of clusters to current 4.1 and have this function_clause:

20:11:33.284 [error] |0000000000|Undefined:Undefined (emulator) Error in process <0.15972.0> on node 'kazoo_apps@tld.com' with exit value:
{function_clause,[{kz_json,filter,[#Fun<kz_custom_sip_headers.1.10974961>,undefined],[{file,"src/kz_json.erl"},{line,574}]},{kz_custom_sip_headers,outbound,2,[{file,"src/kz_custom_sip_headers.erl"},{line,55}]},{stepswitch_resources,gateway_from_jobj,2,[{file,"src/stepswitch_resources.erl"},{line,1132}]},{stepswitch_resources,gateways_from_jobjs,3,[{file,"src/stepswitch_resources.erl"},{line,1105}]},{stepswitch_resources,resource_from_jobj,1,[{file,"src/stepswitch_resources.erl"},{line,1019}]},{stepswitch_resources,create_resource,2,[{file,"src/stepswitch_resources.erl"},{line,914}]},{stepswitch_resources,resources_from_jobjs,2,[{file,"src/stepswitch_resources.erl"},{line,908}]},{stepswitch_resources,fetch_global_resources,0,[{file,"src/stepswitch_resources.erl"},{line,840}]}]}

**Pull request merged**
