### PR TITLE
Fix crossbar_util:response_400

### PR DESCRIPTION
**Pull request by kalda341**

### CODE REVIEW

**Comment by BorigTheDwarf** [comment]
+1

**Comment by fenollp** [comment]
Do you file like this is needed for crossbar modules pre-packaged in Kazoo or more for the ones you might have developed?

**Comment by kalda341** [comment]
@fenollp This is needed wherever resp_error_msg is set in the validation stage. This occurs whenever crossbar_util:response_400 is used, such as in cb_phone_numbers_v2.
This is also used by additional crossbar modules I have developed.

**Comment by lazedo** [comment]
@mark2600 ping
@kalda341 how about fixing in `crossbar_util:response_400` ?

**Comment by mark2600** [comment]
I agree with these changes, we should not clobber an already set error_resp

**Pull request merged**
