### PR TITLE
add comment to cccp pin/cid

### PR DESCRIPTION
**Pull request by onnet**
If user has several pins, it would be convenient to add notes to them..

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Hi @onnet! Typically, fields emitted in a view are also fields that exist in the schema. So adding `doc.comments` to the view while not adding it to the schema, to ensure it is of a valid form, is unusual.

Would you mind adding a `comments` property (and sub-property for a comment) to the schema for cccp?

**Comment by onnet** [comment]
@jamesaimonetti Hi, sure, will do!

**Comment by onnet** [comment]
@jamesaimonetti Done.

**Comment by fenollp** [comment]
Does this have anything to do with https://github.com/2600hz/kazoo/blob/master/applications/crossbar/src/modules/cb_comments.erl ?

**Comment by onnet** [comment]
@fenollp Sounds similar, but no, it is just one more field for cccp docs crossbar_listing view :)

**Comment by jamesaimonetti** [comment]
Merged! Thanks @onnet

**Pull request closed without merging**
