### PR TITLE
Teletype unable to read converted file

### PR DESCRIPTION
**Pull request by tsromana**
Teletype was unable to read converted file because of slow conversion from tiff2pdf, so to slow the read process a timer was added.

### CODE REVIEW

**Comment by fenollp** [comment]
`os:cmd` is synchronous so should return only when `tiff2pdf` returns...
Do you have a non default `"tiff_to_pdf_conversion_command"` setting in `system_configs/fax`?

**Comment by tsromana** [comment]
no its the default command, it seems due to slow write to disk it may be causing issues.

**Comment by lazedo** [comment]
@tsromana i don't see how this changes mitigates the problem reported

**Comment by tsromana** [comment]
@lazedo so basically, when the pdf file is tried to be read, it causes no file error (enoent). so i just added a wait period of few seconds to check if the file exist. As @fenollp the `tiff2pdf` is synchronous which means the issue must be related to disk when the file is not being written  fast enough and the file is being read faster by the process, so just to slow it down a bit i added the sleep.

**Comment by sergey-safarov** [comment]
Similar [issue](https://2600hz.atlassian.net/browse/KAZOO-5354) reported by me

**Comment by tsromana** [comment]
@sergey-safarov that's the exact issue i had, with debian 8 virtualized under openstack. I think it is kind of a disk issue as the file could be read after waiting a few ms, using the commit, most of the code does not even gets `enoent` as the delay to call the new fn is enough to make the file readable.

**Comment by fenollp** [comment]
@tsromana are you happy with the alternative solution discussed in the above JIRA ticket?

**Comment by tsromana** [comment]
@fenollp yea no problem :)

**Pull request closed without merging**
