### PR TITLE
check name against _id of JSON files

### PR DESCRIPTION
**Pull request by fenollp**
Catches errors like file callflows.voicemail.json using `_id` "callflows.language" and ensuing name clashes

### CODE REVIEW

**Comment by lazedo** [comment]
@fenollp LGTM. just one thing, 
i would prefer this rename `...riv/couchdb/views/resource_selectors.json → ...rossbar/priv/couchdb/views/selectors.json` not to occur, `resource_selectors` is more specific

**Comment by fenollp** [comment]
Ready!

**Comment by k-anderson** [comment]
@fenollp rebase me!

**Comment by fenollp** [comment]
@k-anderson done!

**Pull request merged**
