### PR TITLE
add search path for kazoo_documents.hrl

### PR DESCRIPTION
**Pull request by jamhed**

### CODE REVIEW

**Comment by lazedo** [comment]
why are you adding this ? circleci and travis don't complain about it?

**Comment by jamhed** [comment]
I'm unable to compile on my laptop clean reopo checkout with issuing make.

**Comment by lazedo** [comment]
check you kz.mk file. travis and ci, always take a clean copy, right ?

**Comment by fenollp** [comment]
Yep, builds fine from fresh clone here..
What is the issue you have? Which OTP do you have installed? Does your $PWD contain spaces?

**Pull request closed without merging**
