### PR TITLE
KAZOO-3599: remove dead code and call to dead function

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@fenollp merge this then run the xref stuff again. Should be the last step, yes?

**Comment by fenollp** [comment]
Ah! Yes, for #1002 it is. (though I expect unrelated issues from the test suite, which I have been working on)

That's pretty amazing @jamesaimonetti ;)

**Comment by fenollp** [comment]
Wait, you want me to merge this? I have no idea whether removing the amqp publish code is valid (though I searched through the files history and could never find the function's definition…)

I'd be happy to merge. Feels kinda amazing hehe

**Comment by jamesaimonetti** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Le 05/04/2015 09:37 PM, Pierre Fenoll a écrit :
> Wait, you want me to merge this? I have no idea whether removing
> the amqp publish code is valid (though I searched through the files
> history and could never find the function's definition…)
> 
> I'd be happy to merge. Feels kinda amazing hehe
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/2600hz/kazoo/pull/1003#issuecomment-98946873
> 

Do it!

- -- 
James Aimonetti
Lead Systems Architect / Impressionable Scallywag
"I thought I fixed that"

2600Hz | http://2600hz.com
sip:james@2600hz.com
tel:415.886.7905
irc:mc_ @ freenode
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBCAAGBQJVSEypAAoJENTKa+JPXCVgETQH/0bcnzJa3XUkAHjYrvq7baqY
eEWoR1h5oqNLlJ3F+W5iYftcAEv6eoJgsKbKAP9sgWZbr+W3LvB9CUl7mqKoUa8Q
YbdGvN9ONTkMEnNuu80V+3R3GEMNaTC0q6ruOuESE/lmbsc/BFLqKvE1u/mSTOef
aQsPItjHb2MAXMTG7aRFeft7nk8sV6xqBmGLa0svrZ8ZcY5kven6r2AXhWvhTRCv
dusK9J3OiUtWCbdeG6PammsAuX1xnOp8Lku3xZg7ZOfkhRnx9Vz7225Z//qUsNih
DM1b/J8gqJPNuwLKAH7K64zHV+8z0DNCAONXHsNrXOSFLtW/vcVccJJlR6E37gs=
=oQIH
-----END PGP SIGNATURE-----

**Comment by fenollp** [comment]
I did it!

**Pull request merged**
