### PR TITLE
Kz cache ttl

### PR DESCRIPTION
**Pull request by noahmehl**
This is a draft PR while we work out the specifics of how to accomplish this.

### CODE REVIEW

**Comment by noahmehl** [comment]
As discussed with @jamesaimonetti, media_mgr can use: https://github.com/2600hz/kazoo/blob/master/core/kazoo_amqp/src/api/kapi_conf.erl to emit document changes, specifically document deleted when a TTS cache PID is removed.  We can use `TTS` as the database, and the MD5 hash as the document `ID`

We can extend ecallmgr to bind for events of document deleted for the `TTS` database, and the MD5 hash as the document `ID`, by extending cache properties here: https://github.com/2600hz/kazoo/blob/f5e88bc7821b4965e94877cf6659363e820cf8e2/applications/ecallmgr/src/ecallmgr_auxiliary_sup.erl#L31

**Comment by noahmehl** [comment]
@jamesaimonetti it looks like we just needed to update the payload for kz_cache_listener to match the correct document.  Can you please take a look?

**Comment by jamesaimonetti** [comment]
Merged, nice!

**Comment by noahmehl** [comment]
@jamesaimonetti should we submit a PR for master as well?

**Pull request closed without merging**
