### PR TITLE
KAZOO-3214: Crossbar access to third_party_bigcouch call recordings

### PR DESCRIPTION
**Pull request by onnet**

### CODE REVIEW

**Comment by fenollp** [comment]
This PR is a respawn of #688. Please follow the discussion from over there before posting here :)

**Comment by lazedo** [comment]
@onnet this will be included in 4.0 as part of couch library refactoring. is it ok to close ?

**Comment by onnet** [comment]
Yep, I will keep my fingers crossed it wouldn't be forgotten. :)

**Comment by lazedo** [comment]
@onnet new PR https://github.com/2600hz/kazoo/pull/1744

**Pull request closed without merging**
