### PR TITLE
Fix acdc under OTP 20 using gen_statem

### PR DESCRIPTION
**Pull request by danielfinke**
See #4048

### CODE REVIEW

**Comment by fenollp** [comment]
A rebase should fix the Dialyzer issues

**Comment by fenollp** [comment]
Could you also look at 
```
applications/ecallmgr/src/ecallmgr_balance_crawler_fsm.erl
applications/konami/src/konami_code_fsm.erl
applications/konami/src/module/konami_transfer.erl
```
and apply the same transformation (FSM -> gen_statem) there? That would help us a lot!

Can be a 2nd PR if you want.

**Comment by danielfinke** [comment]
@fenollp rebased. I'll start a new branch/PR for those others, will send it in a while

**Comment by fenollp** [comment]
Cool! merging this in the meanwhile :)

**Comment by fenollp** [comment]
Now that https://github.com/2600hz/kazoo/pull/4048 is merged, OTP20 support depends on the fsm -> statem transformation ;)

**Comment by danielfinke** [comment]
Planning on working on it tomorrow!

**Comment by danielfinke** [comment]
@fenollp I've opened a PR for the transformations for those other modules: https://github.com/2600hz/kazoo/pull/4114 :)

**Pull request merged**
