### PR TITLE
KAZOO-3940: hold state for webhooks

### PR DESCRIPTION
**Pull request by siplabs**

### CODE REVIEW

**Comment by lazedo** [comment]
CHANNEL_EXECUTE and CHANNEL_EXECUTE_COMPLETE will put a lot of pressure in webhooks. i don't see any added value in here

**Comment by siplabs** [comment]
soft_hold application can not be tracked without them.

**Comment by lazedo** [comment]
maybe the app should bind to rabbit to get the events or use another way to do it.this really puts a lot of pressure in webhooks. describe your use case in jira.

**Comment by jamesaimonetti** [comment]
I could maybe be on board with CHANNEL_HOLD but will not accept CHANNEL_EXECUTE(_COMPLETE); as @lazedo points out, they are too numerous and would add a disproportionate pressure on resources to the value they provide. Those events should be consumed via blackhole/websocket connections.

Also, please be aware that webhooks has received a modest refactoring in KAZOO-3912 to better support adding new webhooks. I would advise holding off on webhook PRs until that is merged, as things have changed a bit internally.

**Comment by jamesaimonetti** [comment]
@siplabs #1169 is merged. Please rebase and update to use the webhooks_skel (adapted for CHANNEL_HOLD/UNHOLD) to provide a hook for these events. CHANNEL_EXECUTE(_COMPLETE) isn't going to be accepted and should be removed from here.

**Comment by siplabs** [comment]
Will do in couple of days! Thanks!

**Comment by fenollp** [comment]
@siplabs If after the rebase Travis still does not start, close & reopen the PR :)

**Comment by jamesaimonetti** [comment]
@siplabs rebase needed.

**Pull request closed without merging**
