### PR TITLE
Split kz_util

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by k-anderson** [comment]
@fenollp hold off on this until we speak tomorrow, got some script stuff for this.  Start on your tickets ;)

Also, don't merge me yet!

**Comment by fenollp** [comment]
dammit

**Comment by jamesaimonetti** [comment]
kz_endpoint/attributes needs updating

**Comment by fenollp** [comment]
Waiting on https://github.com/2600hz/kazoo/compare/ICE-64

**Comment by jamesaimonetti** [comment]
@fenollp rebase? @k-anderson is this acceptable to merge once rebased?

**Comment by fenollp** [comment]
@k-Anderson to help on the renaming script: http://erlang.org/doc/man/erl_tidy.html

Using options: `[{rename, […]}, idem]`

**Pull request closed without merging**
