### PR TITLE
[4.3] back ported fix of broken rabbitmq redurdancy

### PR DESCRIPTION
**Pull request by sergey-safarov**
After [PR 5712](https://github.com/2600hz/kazoo/pull/5712) (for 4.3 branch after [PR 5742](https://github.com/2600hz/kazoo/pull/5742)) rabbimq redundancy is broken.

For master this fixed at [PR5747](https://github.com/2600hz/kazoo/pull/5747) but not back ported into 4.3 branch.

you can reproduce issue by
*joining two rabbitmq daemon into cluster*
```
/ # rabbitmqctl cluster_status
Cluster status of node 'rabbit@rmq1.kazoo' ...
[{nodes,[{disc,['rabbit@rmq1.kazoo','rabbit@rmq2.kazoo']}]},
 {running_nodes,['rabbit@rmq2.kazoo','rabbit@rmq1.kazoo']},
 {cluster_name,<<"rabbit@rmq2.kazoo">>},
 {partitions,[]},
 {alarms,[{'rabbit@rmq2.kazoo',[]},{'rabbit@rmq1.kazoo',[]}]}]
```

*setting two amq connections in kazoo config.ini*
```sh
[safarov@safarov-dell tmp]$ head /etc/kazoo/core/config.ini 
; section are between [] = [section]
; key = value
; to comment add ";" in front of the line
[amqp]
uri = "amqp://kazoo:change_me@127.0.0.1:15672"
uri = "amqp://kazoo:change_me@127.0.0.1:25672"

[bigcouch]
compact_automatically = true
```

Starting "./scripts/dev-start-apps.sh" and "./scripts/dev-start-ecallmgr.sh" and then checking node status.
all will be as expected.

Then stop one rabbimq and check nodes status.

kapps not not able to see ecallmgr node.

### CODE REVIEW

**Comment by lazedo** [comment]
@sergey-safarov thanks for your PR. what's the `ha` policy configured in this scenario ?

**Comment by lazedo** [comment]
@sergey-safarov and did you try after #5982 ?

**Comment by sergey-safarov** [comment]
Hi Luis
I not tested PR 5982. I tested prevision commit. Will do test of this PR too.

*About HA policy.*
I use standard [rabbitmq:3.6.9-alpine](https://hub.docker.com/_/rabbitmq) docker image with added node clustering and `cluster_partition_handling=autoheal` in rabbimq config.

**Comment by sergey-safarov** [comment]
I found one more issue in this test case.
When connection to failed rabbitmq node is restored (node started again), then `kapps` and `ecallmgr` is lost connectivity.

I have configured ha-policy mode using command
```sh
safarov@safarov-dell security]$ docker exec -it rmq1 sh
/ # rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
Setting policy "ha-all" for pattern [] to "{\"ha-mode\":\"all\",\"ha-sync-mode\":\"automatic\"}" with priority "0" ...
/ # rabbitmqctl list_policies 
Listing policies ...
/	ha-all	all		{"ha-mode":"all","ha-sync-mode":"automatic"}	0
```
Tested on current `master` and `4.3` branches

**Comment by lazedo** [comment]
@sergey-safarov your `policy` is wrong. i'm failing to see how this backport would solve the problem

**Comment by sergey-safarov** [comment]
This back port port solves issue after rabbitmq node is stoped.
But not solves issue when rabbitmq started again.

I have looked into [/kazoo-configs-rabbitmq](https://github.com/2600hz/kazoo-configs-rabbitmq) repo, and not found any settings related to `ha policy`.
Could you say correct policy.

**Comment by sergey-safarov** [comment]
Closing this, because issue fixed by https://github.com/2600hz/kazoo/pull/5987 for `master` branch and https://github.com/2600hz/kazoo/pull/5986 for `4.3` branch.

**Pull request closed without merging**
