### PR TITLE
KAZOO-4509 use cowboy compression

### PR DESCRIPTION
**Pull request by lazedo**

### CODE REVIEW

**Comment by fenollp** [comment]
What about blackhole?

**Comment by fenollp** [comment]
And fax and wh_media_proxy ?

All results of `git grep -InE cowboy:start -- core/ applications/`

**Comment by lazedo** [comment]
@fenollp `blackhole` is another story. `fax` and `wh_media_proxy` are used by infrastructure not by users. this ticket is to address the rest api. users of rest api like `monster-ui` users will benefit from this.

**Comment by fenollp** [comment]
[Since content is compressed iff the client says it supports it](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L766-L775), it should be safe to merge this

**Pull request merged**
