### PR TITLE
Revert "KAZOO-4626: add DELETE to methods with no req body"

### PR DESCRIPTION
**Pull request by fenollp**
This reverts commit 33fb2bad1524db37a99bb4690ee47aade8c4eb98.

### CODE REVIEW

**Comment by lazedo** [comment]
this doesn't fix the invalid json

**Comment by jamesaimonetti** [comment]
NO! Do not revert this. We need to conditionally handle when there's a request body. If you revert this only, DELETE with no request body will fail envelope validation.

**Comment by fenollp** [comment]
How do I fix this then?

**Comment by fenollp** [comment]
Issue being: DELETE phone_numbers/collection needs to allow json body

**Comment by fenollp** [comment]
Closing in favour of https://github.com/2600hz/kazoo/pull/1823

**Pull request closed without merging**
