### PR TITLE
KAZOO-3967: cf-module to branch with b-number.

### PR DESCRIPTION
**Pull request by siplabs**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@siplabs can you explain this module's purpose? How do you anticipate it being used?

**Comment by siplabs** [comment]
Hi. Imagine a top-level callflow with a pattern or number list and some common things. And then branching by b-number to finish the job

**Comment by siplabs** [comment]
please, do not merge yet

**Comment by jamesaimonetti** [comment]
@siplabs how are we looking here?

**Comment by siplabs** [comment]
Will be re-submitted soon.

**Comment by siplabs** [comment]
@jamesaimonetti 
It is ready to merge.

**Pull request merged**
