### PR TITLE
Validate js

### PR DESCRIPTION
**Pull request by fenollp**
Heuristic: looks for JS code in values of JSON files (strings starting with `"function"`).

@lazedo do you think this heuristic misses some JS? Is there JS code in our trunk that doesn't start with `"function"`?

### CODE REVIEW

**Comment by lazedo** [comment]
@fenollp i like this a lot :) 
can you run this in all the views in the repo to make sure it works before merging ?

**Comment by lazedo** [comment]
@fenollp how about adding this to local builds ?

**Comment by fenollp** [comment]
In this PR Travis went through all JSON files of the repo. (see `.travis.yml` in the diff).

Please answer my question: `Is this checking all JS?` (is my heuristic good)

New question now: `should this run only on .json files in views/ ? Probably not given there are views in applications/crossbar/priv/couchdb/account/`

**Comment by lazedo** [comment]
@fenollp well, the diff was only one file. if you're checking all string starting with function then it should be good, but, if you add it to local builds, then you can run it against all views to make sure.

**Comment by fenollp** [comment]
The diff shows one file because it found one bug.

As I said [Travis ran on all json files](https://github.com/2600hz/kazoo/pull/1886/files#diff-354f30a63fb0907d4ad57269548329e3R43) or I misunderstood what you mean by `local builds`?

**Pull request merged**
