### PR TITLE
json encode fails if name field not defined

### PR DESCRIPTION
**Pull request by onnet**
19:21:52.652 [debug] |917aadd804750cc9b3d7b8d6acdb57e1|api_util:1220 (<0.22074.1>) failed to encode response: throw: {error,{invalid_ejson,undefined}} : {[{<<"data">>,{[{<<"total_amount">>,10.0},{<<"services_list">>,[{[{<<"name">>,<<208,146,208,184,209,128,209,130,209,131,208,176,208,187,209,140,208,189,209,139,208,185,32,208,190,209,132,208,184,209,129>>},{<<"quantity">>,1},{<<"rate">>,10.0},{<<"single_discount_amount">>,0.0},{<<"cumulative_discount">>,0},{<<"cumulative_discount_rate">>,0.0},{<<"total_discount">>,0.0},{<<"discounted_item_cost">>,10.0},{<<"item_cost">>,10.0},{<<"pp_rate">>,<<226,130,189,32,49,48,46,48,48>>},{<<"pp_total_discount">>,<<226,130,189,32,48,46,48,48>>},{<<"pp_item_cost">>,<<226,130,189,32,49,48,46,48,48>>},{<<"pp_discounted_item_cost">>,<<226,130,189,32,49,48,46,48,48>>}]},{[{<<"name">>,undefined},{<<"quantity">>,0},{<<"rate">>,0.0},{<<"single_discount_amount">>,0.0},{<<"cumulative_discount">>,0.0},{<<"cumulative_discount_rate">>,0.0},{<<"total_discount">>,0.0},{<<"discounted_item_cost">>,0.0},{<<"item_cost">>,0.0}]}]},{<<"account_id">>,<<"0c237d13a4a9dbe43dfac69e8e890832">>}]}},{<<"timestamp">>,<<"2017-09-27T19:21:52">>},{<<"version">>,<<"4.0.0">>},{<<"node">>,<<"URTCxWBbwKmRbWvSgox1CQ">>},{<<"request_id">>,<<"917aadd804750cc9b3d7b8d6acdb57e1">>},{<<"status">>,<<"success">>},{<<"auth_token">>,<<"eyJhbGciOiJSUzI1NiI.......z6A">>}]}

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@onnet why is `{<<"name">>, undefined}` in your JObj to begin with?

**Comment by onnet** [comment]
@jamesaimonetti I believe this is all mystery. Some strange people call it BUGS :)
Anyway I didn't dig deep enough. Just added doc as it described over here: https://github.com/2600hz/kazoo/blob/master/doc/blog/understanding_rates.md#sample-service-plan
... and got mentioned error...
Lost 15 mins, made this workaround,  decided to save some time for followers...
And yep, agreed, it should be investigated why 'undefined' wasn't filtered out..

**Comment by jamesaimonetti** [comment]
@onnet do you have the full logs of this request? Might provide a hint...

**Comment by onnet** [comment]
@jamesaimonetti No, deleted it already. Will reproduce tomorrow and get back ...

**Comment by jamesaimonetti** [comment]
@onnet ok, would be nice to see. Will merge this as I think you're correct that 'name' is required. But I would hope it would have generated a schema error instead of this JSON encoding crash.

**Comment by jamesaimonetti** [comment]
@onnet just checking if you had a chance to reproduce the full log of this crash?

**Comment by onnet** [comment]
@jamesaimonetti Hi James. Sorry for the delay. Just suddenly got busy with bureaucracy bullshit. Give me one more day and I'll get back to you with logs :).

**Comment by onnet** [comment]
@jamesaimonetti Hi James. Decided to do it asap. Logs could be seen over here: https://gist.github.com/onnet/42cff30dfc64cad77642ecdec41c1085#file-gistfile1-txt
But I should confess, I see now it is not Kazoo fault. 
It is my buggy billing app.
So, probably, this PR should be just closed...
Sorry for bothering you with that.

**Pull request closed without merging**
