### PR TITLE
ensure number db format is sane

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@kalda341 can you apply this and test? I think this catches the issues being seen with refresh/migrate.

**Comment by lazedo** [comment]
@jamesaimonetti do we need a master version just in case?

**Comment by jamesaimonetti** [comment]
i'll check, will add if needed

**Comment by kalda341** [comment]
@jamesaimonetti Working for me!
Thanks heaps.

**Pull request merged**
