### PR TITLE
KAZOO-5271: read numbers in bulk

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Wait a bit on this one

**Comment by lazedo** [comment]
@fenollp don't forget to reverse https://github.com/2600hz/kazoo/pull/3094/commits/68fdae71443497fb0b61ba343fd0634f115dc1c7

**Comment by lazedo** [comment]
@fenollp please make changes only to address `read numbers in bulk`.

**Comment by fenollp** [comment]
Don't merge yet

**Comment by fenollp** [comment]
@lazedo Ready

**Comment by lazedo** [comment]
@fenollp merge but mrc is still wrong, only shows charges for numbers being activated

**Pull request merged**
