### PR TITLE
KAZOO-4671: Hotfix to allow bind to IPv6 socket

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by fenollp** [comment]
Does this force IPv6 or does it fallback to IPv4 or does it do both?

**Comment by sergey-safarov** [comment]
Pierre this pull request allo crossbar to accept connection via IPv6 ("::") and IPv4 ("0.0.0.0") socket. Used dual binding.
It tested on CentOS7 host. But this may generate error for distribs that not support IPv6.

But I think at present time all distribs support IPv6

**Comment by jamesaimonetti** [comment]
@sergey-safarov I'll test this today using Debian Jessie. I think I have a CentOS 6 install somewhere too.

**Comment by jamesaimonetti** [comment]
Works for me on Debian Jessie:

`curl 192.168.1.5:8000` and `curl [2601:1c0:5803:3660:1a03:73ff:fef8:3c0f]:8000` worked fine.

**Pull request merged**
