### PR TITLE
looks like a typo

### PR DESCRIPTION
**Pull request by onnet**
https://github.com/2600hz/kazoo/blob/master/applications/konami/src/module/konami_callflow.erl#L36-L37

### CODE REVIEW

**Comment by lazedo** [comment]
@onnet i don't think it is a typo, `captures` is correct

**Comment by onnet** [comment]
@lazedo Exactly! It was 'captured' previously..

**Comment by onnet** [comment]
@lazedo typo in docs, not in code..

**Comment by lazedo** [comment]
@onnet need to sleep more :)

**Pull request merged**
