### PR TITLE
Add distinctive ring to ring groups

### PR DESCRIPTION
**Pull request by kalda341**
This allows a distinctive ringtone to be set on a ring group.

### CODE REVIEW

**Comment by kalda341** [comment]
Does anyone have any elegant suggestions for how avoid the CI crashing on this code?

**Comment by grahamsnz** [comment]
@kalda341 We have had many clients request this functionality. So far, we've been able to add Caller ID text prefix. Using distinctive rings is much more intuitive for the user.

**Comment by jamhed** [comment]
@kalda341, you need to add missing clause (function you've introduced) to  cf_data_usage.erl

**Comment by jamhed** [comment]
@kalda341, I'm going to look into it, will let you know.

**Comment by jamhed** [comment]
@kalda341, see https://github.com/2600hz/kazoo/pull/3311

**Comment by kalda341** [comment]
@jamhed Do you know what's making the CI fail this time? I've rebased to see if it has been fixed, but no luck.

**Comment by jamesaimonetti** [comment]
@kalda341 merged into master after rebasing and adding some changes to document the fields available in `Data` payload now

**Pull request closed without merging**
