### PR TITLE
Master pr user doc validation

### PR DESCRIPTION
**Pull request by bradfordben**
Moved all doc validation into kazoo_documents from CB. This was requested by @jamesaimonetti in prep for PR https://github.com/2600hz/kazoo/pull/6424

### CODE REVIEW

**Comment by bradfordben** [comment]
Unrelated test failing from what i can tell.

**Comment by lazedo** [comment]
@bradfordben please rebase. thanks

**Comment by bradfordben** [comment]
Rebased on latest master

**Comment by bradfordben** [comment]
Unrelated build issue by the looks of it.

**Comment by lazedo** [comment]
@bradfordben not so sure, this pr does change account stuff and the error is related. latest commit into master passed circleci and i just rebased another branch that also passed circleci. needs attention

**Comment by bradfordben** [comment]
@lazedo the error is really not easy to debug. The DB is returning 500 "unknown_error" when trying to save a doc (smtp log) to an account. I cant see the doc its saving but the account id and doc id its trying to save look to be in a valid format.

Very useful error "unknown_error" from the db!! Is the DB up after the tests are run to see if that account exists or get an idea of the error.

Have you tried to rerun the tests incase it was a db issue?

Im also not to sure how i could create this locally, What make command would i run?

**Comment by lazedo** [comment]
@bradfordben i rerun several times. same error all the time. not saying the issue is in the pr, maybe a delete which triggers a notify that tries to use the deleted doc and then tries to recreate it, but its an issue

**Comment by bradfordben** [comment]
@lazedo Ok thanks il keep digging and see. Ive just rebased off latest master but will try and work out whats going on here. If i dont get it solved by this evening il resubmit on monday to the new repos.

Good luck this weekend with the breakening!

**Comment by lazedo** [comment]
@bradfordben it passed ci. leaving it for @jamesaimonetti to take a final review

**Comment by bradfordben** [comment]
Yeah rebasing worked 👍

**Comment by jamesaimonetti** [comment]
@bradfordben thanks! merged

**Comment by bradfordben** [comment]
Thanks for reviewing.

**Pull request closed without merging**
