### PR TITLE
KAZOO-5133: DANGEROUSLY fix filter_empty

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Extracted from https://github.com/2600hz/kazoo/pull/2748

**Comment by lazedo** [comment]
this needs to be here for a while. we should merge it locally and run it in dev env to see if something comes up.

**Comment by jamesaimonetti** [comment]
I think the intent of filter_empty was to emulate ["falsy"](https://www.sitepoint.com/javascript-truthy-falsy/) values in Javascript. Perhaps we can add a 'filter_falsy' that does what 'filter_empty' did prior to this PR, update all filter_empty to filter_falsy, and then selectively update to the new filter_empty as needed?

**Comment by fenollp** [comment]
Actually, there's all the direct usages of `is_empty/1` too that should probably get converted to `is_falsy/1` (as a first step).

**Comment by k-anderson** [comment]
@fenollp this needs to wait until 4.1+ AND we have a complete make-busy test suite to ensure no unforeseen issues arise from this change ;)

**Pull request merged**
