### PR TITLE
added break action to channels api

### PR DESCRIPTION
**Pull request by tesarm**

### CODE REVIEW

**Comment by lazedo** [comment]
@tesarm you'll need to rebase as you did before.

**Comment by tesarm** [comment]
I don't know what you mean

**Comment by lazedo** [comment]
@tesarm here's how i usually do. create new fork, create new branch in my fork and to the work. open a PR from that branch to 2600hz:master, when accepted, refresh my fork master branch and restart next task. delete my branch for the finished task.

**Comment by tesarm** [comment]
@lazedo  I hope I did it properly now: https://github.com/2600hz/kazoo/pull/1849

I apologise for creating multiple pull requests.

**Pull request closed without merging**
