### PR TITLE
PISTON-835:Posible fix for kz_json:to_map/1 for kz_json:objects() with the same keys

### PR DESCRIPTION
**Pull request by bradfordben**
There is a issue with to_map in kz_json.

```kz_json:to_map([{[{<<"A">>, 1}, {<<"B">>, 2}]}, {[{<<"A">>, 8}, {<<"B">>, 9}]}])```

Will return:

```#{<<"A">> => 8,<<"B">> => 9}```

Possible solution is to return:

```[#{<<"A">> => 8,<<"B">> => 9},#{<<"A">> => 1,<<"B">> => 2}]```

But im open to suggestions. Other option is to just remove the case that deals with lists and cause a crash.

### CODE REVIEW

**Comment by lazedo** [comment]
how about using `jiffy:decode(kz_json:encode(J), [return_maps])` ?

**Comment by bradfordben** [comment]
Looks good. I forgot to look at possible jiffy functions 👍
I have updated the code and pushed a new commit. 
See you at KazooCon

**Comment by jamesaimonetti** [comment]
Added a unit test as well. Merged manually

**Comment by bradfordben** [comment]
Thanks 👍

**Pull request closed without merging**
