### PR TITLE
PISTON-575: ignore non-existent dbs in unassign_from_prev

### PR DESCRIPTION
**Pull request by danielfinke**
When unassigning a number from prev_assigned_to, not_found errors should be ignored when the prev_assigned_to refers to an account that was deleted

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
Would it be worth changing `split_by_prevassignedto/1` to check `kz_datamgr:db_exists/1` as well in the [case statement](https://github.com/2600hz/kazoo/blob/master/core/kazoo_number_manager/src/knm_phone_number.erl#L325)?

**Comment by danielfinke** [comment]
@jamesaimonetti are you thinking to do that as an alternative or an addition

**Comment by jamesaimonetti** [comment]
I was originally thinking instead of, but it certainly doesn't hurt to have both checks. I wasn't sure if the `{error, not_found}` tuple could come from the doc not being found; as far as I recall we didn't have a way to distinguish between "db not found" and "doc not found" but since it uses `kz_datamgr:del_docs/2`, the `not_found` should be for the DB.

So let's do both. :)

**Comment by jamesaimonetti** [comment]
Thanks!

**Pull request closed without merging**
