### PR TITLE
Kazoo 4500 - branch counter on callflows

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by onnet** [comment]
@jamesaimonetti After updating 3.22 to the version with this patch got the next error. Removing this patch resolved this problem. 

Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:786 (<0.6606.2>) authorizing id undefined
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:705 (<0.6606.2>) moving to action 'cf_record_call'
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_media_recording:169 (<0.6616.2>) starting event listener for record_call
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:387 (<0.6606.2>) continuing to child '_'
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:705 (<0.6606.2>) moving to action 'cf_prepend_cid'
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_prepend_cid:26 (<0.6618.2>) update prefix with name: Sales SPB  num: undefined
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:387 (<0.6606.2>) continuing to child '_'
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:705 (<0.6606.2>) moving to action 'cf_callflow'
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_callflow:30 (<0.6623.2>) branching to new callflow ddd984204793f7d13acc877f4500748d
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:429 (<0.6606.2>) callflow has been branched
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_util:147 (<0.6606.2>) stacktrace:
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_util:154 (<0.6606.2>) st: cf_exe:handle_cast/2 at (433)
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_util:154 (<0.6606.2>) st: gen_listener:handle_module_cast/2 at (978)
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_util:154 (<0.6606.2>) st: gen_server:handle_msg/5 at (607)
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|wh_util:154 (<0.6606.2>) st: proc_lib:wake_up/3 at (237)
Jan 17 02:25:54 kz531 2600hz[1776]: |52c0468f-374b-1234-5394-002590f06602|cf_exe:645 (<0.6606.2>) callflow execution has been stopped: badarith
 
Here is a callflow call was branched to:

{[{<<"flow">>,
   {[{<<"children">>,
      {[{<<"6bf8de272f7eb92647fbec3cb2cf72ae">>,
         {[{<<"children">>,
            {[{<<"_">>,
               {[{<<"data">>,
                  {[{<<"name">>,<<"Whole Office">>},
                    {<<"endpoints">>,
                     [{[{<<"endpoint_type">>,<<"group">>},
                        {<<"id">>,<<"38ac2b1633391efe74cd88f3c6ab1b40">>},
                        {<<"delay">>,<<"0">>},
                        {<<"timeout">>,<<"60">>}]},
                      {[{<<"endpoint_type">>,<<"group">>},
                        {<<"id">>,<<"7ad209c537c0184ccd0fa5c565dd93af">>},
                        {<<"delay">>,<<"10">>},
                        {<<"timeout">>,<<"60">>}]}]},
                    {<<"strategy">>,<<"simultaneous">>},
                    {<<"timeout">>,70}]}},
                 {<<"module">>,<<"ring_group">>},
                 {<<"children">>,{[]}}]}},
              {<<"0">>,
               {[{<<"module">>,<<"receive_fax">>},
                 {<<"children">>,{[]}},
                 {<<"data">>,
                  {[{<<"owner_id">>,<<"cef8837e3fbe0083f4542f5bb9e8c648">>},
                    {<<"media">>,{[{<<"fax_option">>,true}]}}]}}]}}]}},
           {<<"data">>,{[{<<"id">>,<<"c405c77a3f35dfdbb1b3ff066907d5a0">>}]}},
           {<<"module">>,<<"menu">>}]}},
        {<<"_">>,
         {[{<<"data">>,{[{<<"id">>,<<"9b31f75790bd7f7cdfdb435f62ba97a1">>}]}},
           {<<"module">>,<<"play">>},
           {<<"children">>,{[]}}]}}]}},
     {<<"data">>,{[{<<"timezone">>,<<"Europe/Moscow">>}]}},
     {<<"module">>,<<"temporal_route">>}]}},
  {<<"numbers">>,[<<"6700">>]},
  {<<"contact_list">>,{[{<<"exclude">>,false}]}},
  {<<"patterns">>,[]},
  {<<"id">>,<<"ddd984204793f7d13acc877f4500748d">>},
  {<<"ui_metadata">>,
   {[{<<"ui">>,<<"kazoo-ui">>},{<<"version">>,<<"Master2014112013:58">>}]}},
  {<<"name">>,<<"Sales">>},
  {<<"metadata">>,
   {[{<<"9b31f75790bd7f7cdfdb435f62ba97a1">>,
      {[{<<"name">>,<<"Non-Working_wav">>},{<<"pvt_type">>,<<"media">>}]}},
     {<<"6bf8de272f7eb92647fbec3cb2cf72ae">>,
      {[{<<"name">>,<<"OfficeHours">>},{<<"pvt_type">>,<<"temporal_rule">>}]}},
     {<<"c405c77a3f35dfdbb1b3ff066907d5a0">>,
      {[{<<"name">>,<<"Sales">>},{<<"pvt_type">>,<<"menu">>}]}}]}}]}

**Comment by jamesaimonetti** [comment]
@onnet Weird, not sure how branch_count could be anything but an integer. Can you modify the [log line here](https://github.com/2600hz/kazoo/blob/3.22/applications/callflow/src/cf_exe.erl#L429) to include the `BC` value? Curious what it was set to to cause the crash.

**Comment by jamesaimonetti** [comment]
Or check `sup whapps_config get_integer callflows max_branch_count`

**Comment by onnet** [comment]
@jamesaimonetti 
[root@kz532 kazoo]# grep "callflow has been branched, BC" /var/log/2600hz/kazoo.log
Jan 17 12:00:21 kz532 2600hz[1771]: |927e26d1-379b-1234-5394-002590f06602|cf_exe:429 (<0.30836.22>) callflow has been branched, BC: undefined
Jan 17 12:00:24 kz532 2600hz[1771]: |927e26d1-379b-1234-5394-002590f06602|cf_exe:429 (<0.31112.22>) callflow has been branched, BC: undefined
Jan 17 12:00:28 kz532 2600hz[1771]: |96e16a5a-379b-1234-5394-002590f06602|cf_exe:429 (<0.31544.22>) callflow has been branched, BC: undefined
Jan 17 12:00:32 kz532 2600hz[1771]: |96e16a5a-379b-1234-5394-002590f06602|cf_exe:429 (<0.31892.22>) callflow has been branched, BC: undefined
[root@kz532 kazoo]# sup whapps_config get_integer callflows max_branch_count
undefined

**Comment by onnet** [comment]
@jamesaimonetti  
[root@kz531 kazoo]# sup whapps_config get_integer callflow max_branch_count
50

**Comment by onnet** [comment]
@jamesaimonetti 
Hi again. The situation occurs when I am using cf_callflow module. On branching to new callflow branch_count is absent in State (take a look around this line: cf_exe:430 (<0.12486.0>) callflow has been branched State#state.branch_count: undefined):

Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:722 (<0.12486.0>) moving to action 'cf_callflow'
Jan 17 13:19:21 kz527 2600hz[2259]: |0000000000|Undefined:Undefined (<0.1257.0>) Supervisor cf_event_handler_sup started wh_media_recording:start_link({whapps_call,<<"c61d6b0b-37a6-1234-d593-a26e12c191c6">>,#Fun<whapps_call.default_helper_function.2>,...}, {[{<<"action">>,<<"start">>},{<<"url">>,<<>>},{<<"format">>,<<"mp3">>},{<<"time_limit">>,<<"6000">>},...]}) at pid <0.12496.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_callflow:30 (<0.12498.0>) branching to new callflow 5ce0833aca9266a1cb852b7e25eddd3c
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:547 (<0.12486.0>) cf module cf_record_call down normally
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:428 (<0.12486.0>) callflow has been branched State#state.flow: {[{<<"module">>,<<"callflow">>},{<<"children">>,{[]}},{<<"data">>,{[{<<"id">>,<<"5ce0833aca9266a1cb852b7e25eddd3c">>}]}}]}
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:429 (<0.12486.0>) callflow has been branched State#state.flows: []
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:430 (<0.12486.0>) callflow has been branched State#state.branch_count: undefined
Jan 17 13:19:21 kz527 2600hz[2259]: |0000000000|Undefined:Undefined (<0.12499.0>) Supervisor {<0.12499.0>,amqp_channel_sup} started amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 94.125.5.27:35442 -> 94.125.5.27:5672">>,280}) at pid <0.12500.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:431 (<0.12486.0>) callflow has been branched NewFlow: {[{<<"module">>,<<"menu">>},{<<"children">>,{[{<<"1">>,{[{<<"module">>,<<"device">>},{<<"children">>,{[]}},{<<"data">>,{[{<<"id">>,<<"c5cc1bf50bcfc78d6970161bf063ff25">>},{<<"timeout">>,<<"20">>},{<<"can_call_self">>,true}]}}]}},{<<"2">>,{[{<<"module">>,<<"receive_fax">>},{<<"children">>,{[]}},{<<"data">>,{[{<<"owner_id">>,<<"c10a3bdfd4baa34c9236749c201064fe">>},{<<"media">>,{[{<<"fax_option">>,true}]}}]}}]}}]}},{<<"data">>,{[{<<"id">>,<<"e5783fe578ad36dfaf0af8204cce0222">>}]}}]}
Jan 17 13:19:21 kz527 2600hz[2259]: |0000000000|Undefined:Undefined (<0.12499.0>) Supervisor {<0.12499.0>,amqp_channel_sup} started amqp_channel:start_link(network, <0.125.0>, 280, <0.12500.0>, {<<"client 94.125.5.27:35442 -> 94.125.5.27:5672">>,280}) at pid <0.12501.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |0000000000|Undefined:Undefined (<0.12499.0>) Supervisor {<0.12499.0>,amqp_channel_sup} started rabbit_writer:start_link(#Port<0.9497>, 280, 131072, rabbit_framing_amqp_0_9_1, <0.12501.0>, {<<"client 94.125.5.27:35442 -> 94.125.5.27:5672">>,280}) at pid <0.12502.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:432 (<0.12486.0>) callflow has been branched State: {state,{whapps_call,<<"c61d6b0b-37a6-1234-d593-a26e12c191c6">>,#Fun<cf_exe.callid.2>,<<"ecallmgr@kz527.onnet.su-<0.6457.0>-395ae687">>,#Fun<cf_exe.control_queue.2>,<<"whistle_apps@kz527.onnet.su-<0.12486.0>-75e36550">>,<<"8129169944">>,<<"88129169944">>,undefined,<<"78122404700">>,<<"freeswitch@kz527.onnet.su">>,<<"kz527.onnet.su">>,<<"sip:mod_sofia@94.125.5.27:11000">>,<<"sip:94.125.5.27:11000">>,<<"78122404700@94.125.5.27">>,<<"+78122404700">>,<<"94.125.5.27">>,<<"88129169944@fs4242.onnet.su">>,<<"88129169944">>,<<"fs4242.onnet.su">>,<<"78122404700@94.125.5.27">>,<<"78122404700">>,<<"94.125.5.27">>,<<"78122404700@94.125.5.27">>,<<"account%2F33%2Fca%2F3929ed585e0e423eb39e4ffe1452">>,<<"33ca3929ed585e0e423eb39e4ffe1452">>,undefined,undefined,undefined,<<"c5e11afa-bd03-11e5-a0bc-593d0533d913">>,undefined,<<"ru-ru">>,<<"callflow">>,<<"0.8.2">>,undefined,{[{<<"Fetch-ID">>,<<"c5e11afa-bd03-11e5-a0bc-593d0533d913">>},{<<"Caller-Privacy-Number">>,false},{<<"Caller-Privacy-Name">>,false},{<<"Account-ID">>,<<"33ca3929ed585e0e423eb39e4ffe1452">>},{<<"Ignore-Display-Updates">>,<<"true">>},{<<"Inception">>,<<"78122404700@94.125.5.27">>},{<<"Application-Node">>,<<"whistle_apps@kz527.onnet.su">>},{<<"Application-Name">>,<<"callflow">>},{<<"Caller-ID-Number">>,<<"88129169944">>},{<<"Caller-ID-Name">>,<<"8129169944">>}]},{[{<<"X-AUTH-PORT">>,<<"5060">>},{<<"X-AUTH-IP">>,<<"94.125.5.106">>}]},[{<<"cf_capture_group">>,undefined},{<<"cf_flow">>,{[{<<"children">>,{[{<<"_">>,{[{<<"module">>,<<"callflow">>},{<<"children">>,{[]}},{<<"data">>,{[{<<"id">>,<<"5ce0833aca9266a1cb852b7e25eddd3c">>}]}}]}}]}},{<<"data">>,{[{<<"action">>,<<"start">>},{<<"url">>,<<>>},{<<"format">>,<<"mp3">>},{<<"time_limit">>,<<"6000">>},{<<"record_on_answer">>,true}]}},{<<"module">>,<<"record_call">>}]}},{<<"cf_flow_id">>,<<"544f6f85c3039f692f9b82c8deeae074">>},{<<"cf_last_action">>,cf_callflow},{<<"cf_metaflow">>,false
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:433 (<0.12486.0>) callflow has been branched BC: undefined
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|gen_listener:990 (<0.12486.0>) handle_cast exception: error: badarith
Jan 17 13:19:21 kz527 2600hz[2259]: |konami_event_listener|wh_amqp_channel:307 (<0.2550.0>) bound whistle_apps@kz527.onnet.su-<0.2550.0>-0946f5e6 to callevt exchange (routing key call.CHANNEL_ANSWER.c61d6b0b-37a6-1234-d593-a26e12c191c6) via channel <0.2331.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|wh_util:150 (<0.12486.0>) stacktrace:
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|wh_util:157 (<0.12486.0>) st: cf_exe:handle_cast/2 at (437)
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|wh_util:157 (<0.12486.0>) st: gen_listener:handle_module_cast/2 at (975)
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|wh_util:157 (<0.12486.0>) st: gen_server:handle_msg/5 at (607)
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|wh_util:157 (<0.12486.0>) st: proc_lib:wake_up/3 at (237)
Jan 17 13:19:21 kz527 2600hz[2259]: |00000000000|wh_amqp_channel:154 (<0.623.0>) published to callctl(amqp://guest:guest@94.125.5.27:5672) exchange (routing key ecallmgr@kz527.onnet.su-<0.6457.0>-395ae687) via <0.1045.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |00000000000|wh_amqp_worker:613 (<0.623.0>) published message 1b1c990579f7a3b9 for <0.12486.0>
Jan 17 13:19:21 kz527 2600hz[2259]: |c61d6b0b-37a6-1234-d593-a26e12c191c6|cf_exe:662 (<0.12486.0>) callflow execution has been stopped: badarith

**Comment by lazedo** [comment]
found it.
https://github.com/2600hz/kazoo/commit/42e5f4b7b3b26041457f11c3b7a586066c2ac043

**Comment by onnet** [comment]
Yep, me too already. Works fine now :)

**Comment by onnet** [comment]
Could you please cherry pick it to 3.22 also?

**Pull request merged**
