### PR TITLE
decode to {} and log input when failing hard

### PR DESCRIPTION
**Pull request by fenollp**
cherry pick of #1668

### CODE REVIEW

**Comment by lazedo** [comment]
i don't agree on this. If a payload is malformed, I would prefer to throw the exception

**Comment by jamesaimonetti** [comment]
I agree, too many chances of defaults being applied to an empty object rather than letting the client know their request was malformed. Let it crash!

**Comment by fenollp** [comment]
I'll rework it. What should I do about this patch in 3.22? (it's there already)

**Comment by fenollp** [comment]
updated as discussed on standup

**Pull request merged**
