### PR TITLE
account_config: generate account schemas

### PR DESCRIPTION
**Pull request by jamhed**

### CODE REVIEW

**Comment by fenollp** [comment]
Does the source part really need to be stored in the JSON? Can't it be guessed from the module name?

**Comment by jamhed** [comment]
@fenollp, what module name?

**Comment by jamhed** [comment]
this will fail circle-ci due to unmerged #3223

**Comment by lazedo** [comment]
@jamhed rebase to fix ci

**Comment by icehess** [comment]
@jamhed what about parsing `kapps_account_config:get/2,3,4` as well?

**Pull request merged**
