### PR TITLE
KAZOO-4460: Hang-Up of the last conference participant doesn't result…

### PR DESCRIPTION
**Pull request by onnet**
… in proper participant_destroy_event publishing.
See https://2600hz.atlassian.net/browse/KAZOO-4460 for more details.

Regards,

### CODE REVIEW

**Comment by lazedo** [comment]
@onnet not sure if this is the right approach to the problem. with this change you are sending the removed participant in the participants list.

can you please try this instead ?
in https://github.com/2600hz/kazoo/blob/master/core/whistle-1.0.0/src/api/wapi_conference.erl
move the `<<"Participants">>` header from `PARTICIPANTS_EVENT_HEADERS` Line ~308 to `OPTIONAL_PARTICIPANTS_EVENT_HEADERS` Line ~309

**Comment by onnet** [comment]
@lazedo This approach also works. Luis, many thanks!!!!

**Comment by lazedo** [comment]
@onnet great. will you update the PR ?

**Comment by onnet** [comment]
With pleasure! :)

**Comment by lazedo** [comment]
@onnet Thank You! (again :) )

**Pull request merged**
