### PR TITLE
Fixed tiff2pdf call on Alpine dist

### PR DESCRIPTION
**Pull request by sergey-safarov**
On Alpine options must goes before input file

### CODE REVIEW

**Comment by lazedo** [comment]
@sergey-safarov doesn't this break other platforms ?

**Comment by sergey-safarov** [comment]
I think no.
Alpine use small, but not so much flexible command line parser. Other platform think use more flexible parser.

**Comment by lazedo** [comment]
@sergey-safarov i'll give a shot and see if it breaks for other platforms

**Comment by lazedo** [comment]
@sergey-safarov @icehess thanks for pr and testing this.

**Pull request merged**
