### PR TITLE
doodle_util was not properly taking the Message Body.  This resulted in ...

### PR DESCRIPTION
**Pull request by aberke**
...sms documents with no body property - a bug

### CODE REVIEW

**Comment by lazedo** [comment]
Hi Alex,
the body is only needed for the initial creation, after that it is taken from pvt_call.
check the views.
would you be more comfortable if we include this ?

**Comment by aberke** [comment]
I don't understand what you mean 
https://github.com/2600hz/kazoo/blob/master/core/kazoo_modb-1.0.0/priv/couchdb/views/sms.json#L5
right?
sms documents have body in the schema but the body is not saved in the SMS document past this point (it is when it's first PUT through crossbar)

**Comment by lazedo** [comment]
the views used to reference the body inside pvt_call, must have changed this :) 
anyway, this will not solve the issue because if you change the body along the flow, the final version will not be saved in the Body field.

add these to doodle_util and remove your change

-export([get_sms_body/1]).  

-spec get_sms_body(whapps_call:call()) -> ne_binary().
get_sms_body(Call) ->
    whapps_call:kvs_fetch(<<"Body">>, Call).


in save_sms/4

--    Body = wh_json:get_value(<<"Body">>, JObj),
++  Body = get_sms_body(Call),

**Comment by aberke** [comment]
I amended the commit

**Comment by lazedo** [comment]
thank you

**Pull request merged**
