### PR TITLE
Kazoo 3839: check JSON files for syntax

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by fenollp** [comment]
I like this :) Is the JSON fields order going to stay the same every time we run `make json` ?

**Comment by jamesaimonetti** [comment]
The JSON structure will be untouched between runs (assuming no changes in the file).

**Comment by jamesaimonetti** [comment]
@fenollp If this works for you (or @lazedo or @macpie), let's merge it and be done with JSON syntax errors!

**Comment by fenollp** [comment]
LGTM

**Pull request merged**
