### PR TITLE
Allow Accounts to have preflows that are executed via doodle (sms) as we...

### PR DESCRIPTION
**Pull request by aberke**
...ll as in callflow application.

### CODE REVIEW

**Comment by lazedo** [comment]
Hi Alex,
can you please keep the same names as in callflow ?
this will help to merge doodle/callflow in the future.
thanks

**Comment by aberke** [comment]
I didn't like that callflow was using functions names like `maybe_exec_preflow` and `exec_preflow` because from what I can tell no callflow execution happens in the route_req.  It seems the execution happens in the route_win.  It takes a lot of reading code to realize this when it could be immediately obvious from the function names.

**Comment by lazedo** [comment]
i agree and i think your function name is better but for the sake of consistency and possible future merge of _exe into a single executor, we do want to keep the same name. you can choose to change the names in callflow.

**Comment by aberke** [comment]
Ok I did :+1:

**Comment by aberke** [comment]
Also just rebased against master to make a nicer branch for you.

**Comment by lazedo** [comment]
thank you

**Pull request merged**
