### PR TITLE
KAZOO-5447: fix KNM release (rm from prev_account_db + conflicts on deletion)

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
wait a bit on this please

**Comment by fenollp** [comment]
This is ready

**Comment by fenollp** [comment]
Wait no it isn't

**Comment by fenollp** [comment]
now it's really ready

**Comment by k-anderson** [comment]
@fenollp missing specs on most new functions....

**Pull request merged**
