### PR TITLE
added ring_all strategy to validator

### PR DESCRIPTION
**Pull request by N4COM**
the 'ring_all' strategy must be added here in order to set it through API

### CODE REVIEW

**Comment by mark2600** [comment]
ACDC does not actually support ring_all

**Comment by N4COM** [comment]
Yes, it does. I developed it months ago.
https://github.com/2600hz/kazoo/commit/d03bbe54ef97fc3653cb1c00ae001d4abbcdb577

**Comment by N4COM** [comment]
> ACDC does not actually support ring_all

Yes, it does. I developed it months ago.
https://github.com/2600hz/kazoo/commit/d03bbe54ef97fc3653cb1c00ae001d4abbcdb577
https://github.com/2600hz/kazoo/blob/master/applications/acdc/src/acdc_queue_manager.erl#L869

**Comment by N4COM** [comment]
Hi, please consider it.
https://github.com/2600hz/kazoo/blob/master/applications/acdc/src/acdc_queue_manager.erl#L873

**Pull request closed without merging**
