### PR TITLE
Training 4.0

### PR DESCRIPTION
**Pull request by jamesaimonetti**
These are the first attempts at converting training docs to 4.x materials. If you have emacs installed, you can navigate to `doc/user_guides/basic/` and run `make docs` to convert the `.org` to PDFs.

### CODE REVIEW

**Comment by fenollp** [comment]
I can't `make docs`!

```shell
make: *** [00_intro.pdf] Error 255
```

```shell
0 basic training_4.0 λ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
0 basic training_4.0 λ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
0 basic training_4.0 λ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by jamesaimonetti** [comment]
Hmm, will have to play with it a bit:

```
> emacs --version
GNU Emacs 25.1.50.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by jamesaimonetti** [comment]
@fenollp can you try again? Should pull in the org files needed for the build job.

**Comment by fenollp** [comment]
```
0 kazoo.git training_4.0 (18.3) ∀ cd doc/user_guides/basic/
0 basic training_4.0 (18.3) ∀ m docs
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50erlang-mode.el (source)...
Error while loading 50erlang-mode: Cannot open load file: no such file or directory, erlang-start
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80
Contacting host: elpa.gnu.org:80
Saving file /home/pete/wefwefwef/kazoo.git/doc/user_guides/basic/11_system_config.tex...
Wrote /home/pete/wefwefwef/kazoo.git/doc/user_guides/basic/11_system_config.tex
Processing LaTeX file ./11_system_config.tex...
PDF file ./11_system_config.pdf wasn't produced
Makefile:18: recipe for target '11_system_config.pdf' failed
make: *** [11_system_config.pdf] Error 255
2 basic training_4.0 (18.3) ∀ which erl
/home/pete/.bin/builds/otp/18.3/bin/erl
```

Not sure if due to erlang.el not being resolved properly or LaTeX failing?

**Comment by jamesaimonetti** [comment]
probably need the tex packages installed?

**Comment by jamesaimonetti** [comment]
I forget which ones. Try:

```
apt-get install texlive-latex-extra texinfo
```

**Comment by fenollp** [comment]
That command worked! Can you add it and document makefile targets in a README.md there?

Also the PDFs are not assembled into 1 big PDF. Is this normal?
Nice work :)

**Comment by fenollp** [comment]
Can't find this in master. Is this normal?

**Pull request closed without merging**
