### PR TITLE
rm-unused-module: remove cdr_deps

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Once this gets merged please upgrade the formater to its latest version.
@jamhed @lazedo that means `rm -rf make/erlang-formatter`

**Comment by lazedo** [comment]
@fenollp thanks. what about the code that got messy with your previous update ?

**Comment by fenollp** [comment]
@lazedo you'll have to be more specific

**Comment by lazedo** [comment]
@fenollp one example
https://github.com/2600hz/kazoo/blob/master/applications/ecallmgr/src/ecallmgr_fs_route.erl#L351
https://github.com/2600hz/kazoo/blob/17603b96872d32521667dd57923dec7f44f192ab/applications/ecallmgr/src/ecallmgr_fs_route.erl#L351

if you edit the file in github you'll see the tabs

**Comment by fenollp** [comment]
I am not able to grep for tabs in your files. I have however run a full sweep fmt and found 2 files that got through. PR is #2257

> if you edit the file in github you'll see the tabs

Really? All I see is github's coloring of spaces

**Pull request merged**
