### PR TITLE
26203: add source_ip to registration query responses

### PR DESCRIPTION
**Pull request by mark2600**

### CODE REVIEW

**Comment by mark2600** [comment]
NOTE, there is an associated pull request on kazoo-configs that must be accepted with this

**Comment by lazedo** [comment]
@mark2600 don't you need top add `Source-IP`to `kapi_registration` ?
also, maybe we can reuse the existing  `<<"Network-IP">>, <<"Network-Port">>` ?

**Comment by k-anderson** [comment]
@mark2600 IP and port please :)  are these the received parameter from kamailio?

**Comment by mark2600** [comment]
Yes they are passed straight through from Kamailio

**Pull request merged**
