### PR TITLE
Access to "pvt_" fields in "limits" document for user/reseller.

### PR DESCRIPTION
**Pull request by skorobkov**
User can view some pvt_ fileds (`system_config/crossbar.limits/leak_pvt_fields`)
Reseller can view/edit some pvt_ fileds (`system_config/crossbar.limits/reseller_pvt_fields`)
By default it `allow_prepay`, `allow_postpay` and `max_postpay_amount` fields.

If reseller dont set some field (listed in reseller_pvt_fields), ten this "pvt_" field will be removed from "limits" document".

### CODE REVIEW

**Comment by fenollp** [comment]
@Dinkor Don't mind me, trying to get Travis to check your PR…

**Comment by Dinkor** [comment]
i wonder, maybe this should be more "global"? To allow reseller change pvt_* fields in account/user/device/etc documents.

**Comment by k-anderson** [comment]
@Dinkor I would be interesting in discussing a more generic way to do this before our cb_* modules have a lot of 'leaks' ;) 

As, what is the use case that you need the pvt_ fields for limits?

**Comment by Dinkor** [comment]
`pvt_postpay_allow` and `pvt_max_postpay_mount` for account.
Is there some other way (not `limit` doc) for allowing postpay to account?

**Comment by jamesaimonetti** [comment]
@k-anderson was there more to do here with @Dinkor to get this accepted?

**Comment by k-anderson** [comment]
@skorobkov I created a counter-proposal to address the concerns here.  Take a look at https://github.com/2600hz/kazoo/pull/1691 and lets continue the discussion there!

**Pull request closed without merging**
