### PR TITLE
KAZOO-4362: releases & build system refactor

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
@jamesaimonetti could you help me get `rabbitmq` to work again? The releases used to connect successfully but after rebase they don't want to anymore…

**Comment by fenollp** [comment]
Build is failing as a dep fails to build for 15. I let it fail to show it's not yet mergeable

**Comment by fenollp** [comment]
So right now 2 releases are built by `make all clean-releases releases`:
1. whistle_apps
1. ecallmgr

They are basically `Base ++ [whistle_apps]` and `Base ++ [ecallmgr]`
Find out more in `rel/relx.config.src`

Note that the rabbitmq client is now just a client, not a whole server + client anymore. That is not why I'm asking to test it (I know it works), my vm is just capricious. 

What i think is going to happen though is that apps may not start properly (everything somehow waits for the rabbitmq connection). 
But if we merge both releases into just one and have ecallmgr and whiste_apps to work together (which I believe is already the case actually)... Wait. I may just need to merge the both releases into just one. No more `whapps_controller` issues for the `application_controller`. 

Before now, we were starting apps with our controller, unfortunately (or not) OTP's application_controller is doing this job automatically in releases. So I believe we have to switch completely to it for everything to be happy (and that means we get relups). 
That means (take a look at today's commits) relying on the app.src `mod` cb module and removing the `start_deps` code from AppDir/src/App.erl to replace whapps_controller with OTP's way.

**Comment by fenollp** [comment]
And in the end `scripts/dev-start-*.sh` and `scripts/conn-to-*.sh` will be replaced by `make REL=* ACT=start rl` and `make REL=* ACT=attach rl` where `*` is either `whistle_apps` or `ecallmgr`

**Comment by fenollp** [comment]
So @jamesaimonetti, for now make sure that `make all releases ACT=start rl` and the logs look right. 

I'll play with merging releases [on my] tomorrow. 

Please AMA and complain a lot and express your ideas. I'm really slowed down at this point (not going anywhere fast). 

Thx<3

**Comment by jamesaimonetti** [comment]
@fenollp Fixed some DTH issues.

Failing to include erlydtl_parser.erl; with erlydtl (needed by notify, teletype to name two). Your changes to the makefile in erlydtl don't build the erlydtl_parser.yrl, which means the .erl isn't compiled to .beam.

I'll try to fix it this eve, but if not, you have something to do! :)

**Comment by fenollp** [comment]
@jamesaimonetti `grep` for `COMPILE_MOAR`, or I think setting `SOURCES = src/*.yrl src/*.erl` should suffice

**Comment by fenollp** [comment]
@jamesaimonetti Halp! I fixed the declaration of dependencies of pusher's apns. So now the build system knows apns depends on jsx.. but we do not include jsx.

Also, I did not identify what is depending on eiconv.
Also, we have mustache, couldn't we only use it and drop erlydtl?

**Comment by jamesaimonetti** [comment]
@fenollp not sure on eiconv. You can file a ticket for replacing erlydtl with mustache, but several apps use it, not least of which is teletype, so pretty important to be able to render the existing templates as before.

Not sure the story on jsx being used by apns. Maybe @lazedo can shed light there? pusher is still alpha as far as I know, so no biggie yet for building it properly.

**Comment by fenollp** [comment]
Will write a ticket.

@lazedo never mind, jsx is not needed actually.

**Comment by fenollp** [comment]
@jamesaimonetti I believe this is ready!

**Comment by fenollp** [comment]
Dang. Who merged something!? (rebasing…)

**Comment by jamesaimonetti** [comment]
@fenollp Pushed!

Things still require manual intervention to start the `whistle_apps` application. When I run `make clean-release build-release ACT=console release` after building kazoo, I get dropped into a shell:

```
james@dev001:~/local/git/2600hz/kazoo$ make clean-release build-release ACT=console release
rm -r _rel/
rm rel/relx.config
./scripts/src2any.escript rel/relx.config.src

./utils/relx/relx --config rel/relx.config -V 2 release --relname 'kazoo'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/james/local/git/2600hz/kazoo/applications
          /home/james/local/git/2600hz/kazoo/core
          /home/james/local/git/2600hz/kazoo/deps
          /home/james/local/git/2600hz/kazoo/deps/rabbitmq_erlang_client-3.6.0/deps
          /usr/local/lib/erlang/lib
===> Resolved kazoo-4.0.0
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
Exec: /home/james/local/git/2600hz/kazoo/_rel/kazoo/erts-7.2/bin/erlexec -boot /home/james/local/git/2600hz/kazoo/_rel/kazoo/releases/4.0.0/kazoo -boot_var ERTS_LIB_DIR /home/james/local/git/2600hz/kazoo/_rel/kazoo/erts-7.2/../lib -config /home/james/local/git/2600hz/kazoo/_rel/kazoo/releases/4.0.0/sys.config.2.config -args_file /home/james/local/git/2600hz/kazoo/_rel/kazoo/releases/4.0.0/vm.args.2.config -- console
Root: /home/james/local/git/2600hz/kazoo/_rel/kazoo
/home/james/local/git/2600hz/kazoo/_rel/kazoo
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:24:24] [async-threads:25] [hipe] [kernel-poll:true]

Eshell V7.2  (abort with ^G)
(whistle_apps@dev001.2600hz.com)1> 
```

Strangely enough, gcm and apns are started:

```
(whistle_apps@dev001.2600hz.com)1> application:which_applications().
[{gcm,"An Erlang client for Google Cloud Messaging (GCM)",
      "1.0.0"},
 {apns,[],"1.0.2"},
 {ssl,"Erlang/OTP SSL application","7.2"},
 {public_key,"Public key infrastructure","1.1"},
 {compiler,"ERTS  CXC 138 10","6.0.2"},
 {syntax_tools,"Syntax tools","1.7"},
 {sasl,"SASL  CXC 138 11","2.6.1"},
 {crypto,"CRYPTO","3.6.2"},
 {xmerl,"XML parser","1.3.9"},
 {inets,"INETS  CXC 138 49","6.1"},
 {asn1,"The Erlang ASN1 compiler version 4.0.1","4.0.1"},
 {stdlib,"ERTS  CXC 138 10","2.7"},
 {kernel,"ERTS  CXC 138 10","4.1.1"}]
```

But nothing else of interest. Manually starting the `whistle_apps` application also fails to implicitly start the apps listed in `whistle_apps.app`:

```
(whistle_apps@dev001.2600hz.com)2> application:start(whistle_apps).
{error,{not_started,syslog}}
```

Running `application:ensure_all_started/1` does start things successfully:

```
(whistle_apps@dev001.2600hz.com)3> application:ensure_all_started(whistle_apps).
17:40:04.707 [info] Application lager started on node 'whistle_apps@dev001.2600hz.com'
17:40:04.707 [info] Application lager_syslog started on node 'whistle_apps@dev001.2600hz.com'
17:40:04.707 [info] Application poolboy started on node 'whistle_apps@dev001.2600hz.com'
17:40:04.707 [info] Application rabbit_common started on node 'whistle_apps@dev001.2600hz.com'
17:40:04.720 [info] Application amqp_client started on node 'whistle_apps@dev001.2600hz.com'
17:40:04.807 [info] waiting for first amqp connection...
17:40:05.047 [info] successfully connected to 'amqp://guest:guest@localhost:5672'
17:40:07.991 [info] Application whistle_amqp started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.013 [info] Application couchbeam started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.108 [info] waiting for first bigcouch/haproxy connection...
17:40:08.147 [info] connected successfully to localhost:5984
17:40:08.688 [info] Application whistle_couch started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.718 [info] Application whistle_config started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.719 [info] Application braintree started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.719 [info] Application kazoo_modb started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.772 [info] loaded configs from file /etc/kazoo/config.ini
getting services sync_services
not starting sync services
started add_rountine in <0.1134.0>
17:40:08.793 [info] Application whistle_services started on node 'whistle_apps@dev001.2600hz.com'
17:40:08.838 [info] setting whistle_apps cookie to change_me
17:40:08.838 [info] updated console_log to level notice
17:40:08.840 [notice] Changed loglevel of log/error.log to error
{ok,[syslog,ibrowse,kazoo_documents,whistle,lager,
     lager_syslog,poolboy,rabbit_common,amqp_client,whistle_amqp,
     couchbeam,whistle_couch,whistle_config,braintree,kazoo_modb,
     whistle_services,whistle_apps]}
(whistle_apps@dev001.2600hz.com)4> 17:40:08.943 [notice] auto-started whapps [sysconf]
```

From here I can use whapps_controller as expected.

**Comment by jamesaimonetti** [comment]
So, I leave it in your hands to figure out why `whistle_apps` won't start!

**Comment by jamesaimonetti** [comment]
Bon chance!

**Comment by fenollp** [comment]
@jamesaimonetti I don't see where acdc_init:start_link/0 is called?

**Comment by jamesaimonetti** [comment]
@fenollp [here](https://github.com/2600hz/kazoo/blob/KAZOO-4362/applications/acdc/src/acdc_sup.erl#L27) ?

**Comment by fenollp** [comment]
Ah right.
But doesn't the start order matter? ie: shouldn't this be part of acdc_sup:init ?

**Comment by jamesaimonetti** [comment]
I could see moving the `declare_exchanges` before the spawn in start_link.

**Comment by fenollp** [comment]
I'll do it!

**Comment by fenollp** [comment]
I'm not done yet ;)

**Comment by jamesaimonetti** [comment]
When shutting the node down, I'm seeing:

```
(whistle_apps@dev001.2600hz.com)21> 09:03:47.273 [error] gen_server <0.1063.0> terminated with reason: {'module could not be loaded',[{rabbit_amqqueue,notify_sent_queue_down,[<0.1159.0>],[]},{amqp_channel,handle_info,2,[{file,"src/amqp_channel.erl"},{line,533}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```
Strange for that module to not be loaded, no?

**Comment by fenollp** [comment]
FINISHED

**Comment by k-anderson** [comment]
@fenollp OH NO, needs rebase... so close....

**Comment by fenollp** [comment]
haha. Was writing doc anyway

**Comment by fenollp** [comment]
@k-anderson rebased!

**Comment by fenollp** [comment]
holly hell this is real

**Pull request merged**
