### PR TITLE
fix kz_att_http settings from recordings

### PR DESCRIPTION
**Pull request by lazedo**

### CODE REVIEW

**Comment by sergey-safarov** [comment]
Yes, this is fixed issue.

**Comment by sergey-safarov** [comment]
Before i tested PR on my test server. After installing fix on productions server issue is still exist.
```
Jan 16 05:32:13 kazoo-app02.cloudpbx.ai.co.uk sh[13315]: 05:32:13.921 error kz_att_http.78 CRASH REPORT Process <0.4225.1> with 0 neighbours crashed with reason: no function
 clause matching kz_att_http:format_verb(put) line 78
Jan 16 05:32:13 kazoo-app02.cloudpbx.ai.co.uk sh[13315]: 05:32:13.922 error Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[kz_media_proxy
,<0.4224.1>,1,<0.4225.1>,function_clause,[{kz_att_http,format_verb,[put],[{file,"src/kz_att_http.erl"},{line,78}]},{kz_att_http,put_attachment,6,[{file,"src/kz_att_http.erl"
},{line,46}]},{kzs_attachments,put_attachment,6,[{file,"src/kzs_attachments.erl"},{line,138}]},{kz_media_store_proxy,store,4,[{file,"src/kz_media_store_proxy.erl"},{line,285
}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"s..."},...]},...]]},...}}
```

**Comment by lazedo** [comment]
@sergey-safarov did you restart the nodes or made a hotload ? did you restart/hotload all nodes ? because the origin kzc_recording & kz_endpoint_recording will only pass `put` as binary

**Comment by sergey-safarov** [comment]
I restarted both kapps nodes in cluster and executed `sup kapps_maintenance refresh`.
Is possible 'sup kapps_maintenance refresh' leads to this error?

**Comment by sergey-safarov** [comment]
I restarted only kapps, ecallmgr is used without fix.

**Comment by lazedo** [comment]
if you don't want to restart `ecallmgr` but the code was updated you can try to
`sup -n ecallmgr kazoo_maintenance hotload kzc_recording`
`sup -n ecallmgr kazoo_maintenance hotload kz_endpoint_recording`

but this is not the place `chat` :)
you can reach us in irc `2600hz`

**Pull request merged**
