### PR TITLE
Telnyx e911 + KAZOO-4356 (Vitelity's)

### PR DESCRIPTION
**Pull request by fenollp**
Adds Telnyx's E911 module.

Notes:

* uses account config `allowed_features` in place of system config `providers` list
* introduces account config fields: `cnam_provider` & `e911_feature`

### CODE REVIEW

**Comment by fenollp** [comment]
Ready!

**Comment by fenollp** [comment]
I lied: not ready!

**Comment by fenollp** [comment]
New note: adds a _read_only field `features_available`: lists features a number is allowed (by the reseller of the account it is assigned to) to have.

Ex:

```json
    "data": {
        "_read_only": {
            "created": 63643806030,
            "features": [
                "telnyx_e911"
            ],
            "features_available": [
                "cnam",
                "failover",
                "port",
                "prepend",
                "telnyx_e911"
            ],
            "modified": 63643806030,
            "state": "in_service"
        },
        "features": [
            "telnyx_e911"
        ],
        "id": "+13129677542",
        "state": "in_service",
        "telnyx_e911": {
            "locality": "san francisco",
            "postal_code": "94123",
            "region": "ca",
            "street_address": "301 marina blvd."
        }
    },
```

**Comment by lazedo** [comment]
the `telnyx_e911` should be `e911`.
the underlying implementation on the server side should take care of properly map the `e911` feature to the configured provider by the reseller.  
````
 "features_available": [
                "cnam",
                "failover",
                "port",
                "prepend",
                "telnyx_e911"
            ],
```

**Comment by fenollp** [comment]
@lazedo Done

**Pull request merged**
