### PR TITLE
KAZOO-3930: segregate federated messages to have better control over AMQP bus

### PR DESCRIPTION
**Pull request by lazedo**
do not merge yet

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
@lazedo is this ready for review/merge?

**Comment by jamesaimonetti** [comment]
@lazedo ready for review/merge?

**Comment by lazedo** [comment]
@jamesaimonetti waiting for @k-anderson

**Comment by jamesaimonetti** [comment]
@lazedo gotcha. In the mean time, I updated a few spots with dialyzer's help, refactored some big functions into smaller ones, and did some formatting. Hopefully Travis agrees! Let me know how I can help test this code too.

**Comment by jamesaimonetti** [comment]
@lazedo needs rebasing; @k-anderson please review (or let me know what to look for specifically) once rebased.

**Comment by jamesaimonetti** [comment]
@lazedo want to rebase and we can harass @k-anderson to review it?

**Comment by lazedo** [comment]
@jamesaimonetti the main reason for this PR (split local/federated messages) was to get a way to make kamailio work in federation mode. the last build of kamailio already supports federation, so i think this can be closed. however you do have very good commits in this PR and we could use them.
i'll close the PR and leave the branch untouched so we can reuse some of the code.

this theme may come again when we think in zone aggregates or big zones in which we will want to find a way to segregate amqp traffic.

**Pull request closed without merging**
